const getWordBank = () => (() => {
  let nonUndef = (t) => { if (!t) throw new Error(); return t; };

  let m = (english, romaji, kana, kanji) => {
    return {
      EN: english,
      RO: romaji,
      KA: kana,
      KJ: nonUndef(kanji),
    };
  };

  let k = (kanji, romaji, kana, english) => m(nonUndef(english), romaji, kana, kanji);
  let coto1 = (romaji, kanji, kana, english) => m(nonUndef(english), romaji, kana, kanji);

  let createSet = (name, id, words) => {
    let idAlloc = 1;
    return {
      name,
      id,
      words: words.map(word => ({ ...word, id: id + ':' + idAlloc++ })),
    }
  };

  let output = [
    createSet('Daily Nouns', 'daily_nouns', [
      m('analysis', 'bunseki', 'ぶんせき', '分析'),
      m('effort, endeavor', 'doryoku', 'どりょく', '努力'),
      m('study; learning; tutorial', 'gakushuu', 'がくしゅう', '学習'),
      m('entry; filling in; filling out', 'kinyuu', 'きにゅう', '記入'),
      m('cooperation; collaboration', 'kyouryoku', 'きょうりょく', '協力'),
      m('growth; development; growing up; becoming an adult', 'seichou', 'せいちょう', '成長'),
      k('集中','shuuchuu', 'しゅうちゅう', 'concentration; focusing; centralization; integration'),
      k('運転','unten','うんてん','operation; driving'),
      k('外出','gaishutsu','がいしゅつ','going out; outing; leaving'),
      k('博物館','hakubutsukan','はくぶつかん','museum'),
      k('会員',"kai'in", 'かいいん','member'),
      k('会計','kaikei','かいけい','finance; account; treasurer; bill'),
      k('権利','kenri','けんり','right; privilege'),
      k('記事','kiji','きじ','article; news story; report; account'),
      k('能力','nouryoku','のうりょく','ability; faculty'),
      k('入場','nyuujou','にゅうじょう','entrance; admission; entering'),
      k('連続','renzoku','れんぞく','continuation; succession; series'),
      k('作品','sakuhin','さくひん','work of art; performance'),
      k('資本','shihon','しほん','funds; capital'),
      k('集団','shuudan','しゅうだん','group; mass'),
      k('余分','yobun','よぶん','extra; excess; surplus'),
    ]),
    createSet('IT words', 'it_words', [
      coto1('puroguramu', '–', 'プログラム', '(Computer) Program'),
      coto1('apuri', '–', 'アプリ', 'App'),
      coto1('burauza', '–', 'ブラウザ', 'Browser'),
      coto1('konpyuuta', '–', 'コンピュータ', 'Computer'),
      coto1('henkan', '変換', 'へんかん', 'Convert'),
      coto1('deita', '–', 'データ', 'Data'),
      coto1('desukutoppu', '–', 'デスクトップ', 'Desktop'),
      coto1('debaisu', '機器/デバイス', 'きき/デバイス', 'Device'),
      coto1('meiru', '–', 'メール', 'Email'),
      coto1('kakuchoushi', '拡張子', 'かくちょうし', 'File extension'),
      coto1('kansuu', '関数', 'かんすう', 'Function'),
      coto1('haadodoraibu', '–', 'ハードドライブ', 'Hard Drive'),
      coto1('haadouea', '–', 'ハードウエア', 'Hardware'),
      coto1('nyuuryoku', '入力', 'にゅうりょく', 'Input, to fill in'),
      coto1('intaanetto', '–', 'インターネット', 'Internet'),
      coto1('aipiadoresu', '–', 'IPアドレス', 'IP Address'),
      coto1('kiiboudo', '–', 'キーボード', 'Keyboard'),
      coto1('rapputoppu', '–', 'ラップトップ', 'Laptop'),
      coto1('kaisetsusho', '解説書', 'かいせつしょ', 'Manual'),
      coto1('monitaa', '–', 'モニター', 'Monitor'),
      coto1('mausu', '–', 'マウス', 'Mouse'),
      coto1('shutsuryoku', '出力', 'しゅつりょく', 'Output'),
      coto1('purintaa', '–', 'プリンター', 'Printer'),
      coto1('saikidou', '再起動', 'さいきどう', 'Restart'),
      coto1('uwagaki hozon', '(上書き) 保存', '(うわがき) ほぞん', 'Save'),
      coto1('gamen', '画面', 'がめん', 'Screen'),
      coto1('saabaa', '–', 'サーバー', 'Server'),
      coto1('settei', '設定', 'せってい', 'Settings'),
      coto1('supeisu/kuuhaku', 'スペース/空白', 'スペース/くうはく', 'Space'),
      coto1('kidou', '起動', 'きどう', 'Startup'),
      coto1('gijutsu', '技術', 'ぎじゅつ', 'Technology'),
      coto1('tanmatsu', '端末', 'たんまつ', 'Terminal'),
      coto1('tenpu', '添付', 'てんぷ', 'To attach'),
      coto1('asshuku', '圧縮', 'あっしゅく', 'To compress'),
      coto1('setsuzoku', '接続', 'せつぞく', 'To connect'),
      coto1('kopipe', '–', 'コピペ', 'To copy and paste'),
      coto1('kiritoru', '切り取る', 'きりとる', 'To cut'),
      coto1('kakidasu', '書き出す', 'かきだす', 'To export'),
      coto1('sounyuu', '挿入', 'そうにゅう', 'To insert'),
      coto1('haritsukeru', '貼り付ける', 'はりつける', 'To paste'),
      coto1('insatsu', '印刷', 'いんさつ', 'To print out'),
      coto1('kyouyuu', '共有', 'きょうゆう', 'To share'),
      coto1('kidou', '起動', 'きどう', 'To startup'),
      coto1('douki', '同期', 'どうき', 'To synchronize'),
      coto1('tacchipaddo', '–', 'タッチパッド', 'Touchpad'),
      coto1('uebusaito', '–', 'ウェブサイト', 'Website'),
    ]),
    createSet('Programming', 'programming', [
      coto1('', '追加', 'ついか', 'Add'),
      coto1('hiksuu', '引数', 'ひきすう', 'Argument, parameter'),
      coto1('hairetsu', '配列', 'はいれつ', 'Array'),
      coto1('jinkouchinou', '人工知能', 'じんこうちのう', 'Artificial intelligence, AI'),
      coto1('hidouki', '非同期', 'ひどうき', 'Asynchronous'),
      coto1('bakkendo', '–', 'バックエンド', 'Backend'),
      coto1('beitaban', 'ベータ版', 'ベータばん', 'Beta version'),
      coto1('bainari', '–', 'バイナリー', 'Binary'),
      coto1('nishinsuu', '二進数', 'にしんすう', 'Binary number'),
      coto1('bitto', '–', 'ビット', 'Bit'),
      coto1('buuru', '–', 'ブール', 'Boolean'),
      coto1('shingichi/shinrichi', '真偽値/真理値', 'しんぎち/しんりち', 'Boolean value'),
      coto1('bagu', '–', 'バグ', 'Bug'),
      coto1('birudo', '–', 'ビルド', 'Build (noun)'),
      coto1('kouru', '–', 'コール', 'Call'),
      coto1('moji', '文字', 'もじ', 'Character'),
      coto1('kurasu', '–', 'クラス', 'Class'),
      coto1('koudorebyuu', '–', 'コードレビュー', 'Code Review'),
      coto1('komandorain', '–', 'コマンドライン', 'Command Line'),
      coto1('konpairusuru', '–', 'コンパイルする', 'Compile'),
      coto1('sakusei', '作成', 'さくせい', 'Compose/create'),
      coto1('joukentsuki', '条件つき', 'じょうけんつき', 'Conditional'),
      coto1('teisuu', '定数', 'ていすう', 'Constant'),
      coto1('deitakouzou', 'データ構造', 'データこうぞう', 'Data Structure'),
      coto1('deitashurui', 'データ種類', 'データしゅるい', 'Data Type'),
      coto1('deitabeisu', '–', 'データベース', 'Database'),
      coto1('debaggu', '–', 'デバッグ', 'Debug'),
      coto1('debaggusuru', '–', 'デバッグする', 'Debugging'),
      coto1('sengen', '宣言', 'せんげん', 'Declaration'),
      coto1('fukugou', '復号', 'ふくごう', 'Decryption'),
      coto1('teigi', '定義', 'ていぎ', 'Define'),
      coto1('nouhin', '納品', 'のうひん', 'Delivery'),
      coto1('haibi', '配備', 'はいび', 'Deploy'),
      coto1('sekkei', '設計', 'せっけい', 'Design/architecture'),
      coto1('kaihatsusha', '開発者', 'かいはつしゃ', 'Developer'),
      coto1('kaihatsu', '開発', 'かいはつ', 'Development'),
      coto1('kaihatsukankyou', '開発環境', 'かいはつかんきょう', 'Development environment'),
      coto1('douteki', '動的', 'どうてき', 'Dynamic'),
      coto1('angouka', '暗号化', 'あんごうか', 'Encryption'),
      coto1('eraa', '–', 'エラー', 'Error'),
      coto1('ibento', '–', 'イベント', 'Event'),
      coto1('ibentohandoraa', '–', 'イベントハンドラー', 'Event Handler'),
      coto1('reigai', '例外', 'れいがい', 'Exception'),
      coto1('fureimuwaaku', '–', 'フレームワーク', 'Framework'),
      coto1('furontoendo', '–', 'フロントエンド', 'Front End'),
      coto1('furusutakku', '–', 'フルスタック', 'Full Stack'),
      coto1('kinou', '機能', 'きのう', 'Function'),
      coto1('kansuu', '関数 ', 'かんすう', 'Function'),
      coto1('HTTP rikuesuto', '–', 'HTTPリクエスト', 'HTTP Request'),
      coto1('jissou', '実装', 'じっそう', 'Implementation'),
      coto1('nyuuryoku', '入力', 'にゅうりょく', 'Input'),
      coto1('seisuu (gata)', '整数 (型)', 'せいすう (がた)', 'Integer (type)'),
      coto1('ruupu', '–', 'ループ', 'Loop'),
      coto1('kikaigakushuu', '機械学習', 'きかいがくしゅう', 'Machine Learning'),
      coto1('hoshu', '保守', 'ほしゅ', 'Maintenance'),
      coto1('kanri', '管理', 'かんり', 'Manage'),
      coto1('nyuurarunettowaaku', '–', 'ニューラルネットワーク', 'Neural Network'),
      coto1('nuru', '–', 'ヌル', 'Null'),
      coto1('obujekuto', '–', 'オブジェクト', 'Object'),
      coto1('obujekutoshikou', 'オブジェクト指向', 'オブジェクトしこう', 'Object-oriented'),
      coto1('unyou', '運用', 'うんよう', 'Operation'),
      coto1('enzanshi', '演算子', 'えんざんし', 'Operator'),
      coto1('autoputto', '–', 'アウトプット', 'Output'),
      coto1('heiretsushori', '並列処理', 'へいれつしょり', 'Parallel processing'),
      coto1('parameita', '–', 'パラメータ', 'Parameter'),
      coto1('pursesu/shori', 'プロセス/処理', 'プロセス/しょり', 'Process'),
      coto1('puroguramingu', '–', 'プログラミング', 'Programming'),
      coto1('konpyuutaagengo', 'コンピューター言語', 'コンピューターげんご', 'Programming language'),
      coto1('gijiransuu', '擬似乱数', 'ぎじらんすう', 'Pseudo-random number'),
      coto1('ransuu', '乱数', 'らんすう', 'Random number'),
      coto1('shouchousei', '冗長性', 'じょうちょうせい', 'Redundancy'),
      coto1('jikkou', '実行 ', 'じっこう', 'Run/execute'),
      coto1('sekyuritii', '–', 'セキュリティー', 'Security'),
      coto1('sofutouea', '–', 'ソフトウェア', 'Software'),
      coto1('sousu', '–', 'ソース', 'Source'),
      coto1('shou', '仕様', 'しよう', 'Specification'),
      coto1('supurinto', '–', 'スプリント', 'Sprint'),
      coto1('suteitomento', '–', 'ステートメント', 'Statement'),
      coto1('seiteki', '静的', 'せいてき', 'Static'),
      coto1('teishi', '停止', 'ていし', 'Stop'),
      coto1('kijiretsu', '文字列', 'もじれつ', 'String'),
      coto1('kouzou', '構造', 'こうぞう', 'Structure'),
      coto1('tagu', '–', 'タグ', 'Tag'),
      coto1('tesuto', '–', 'テスト', 'Test'),
      coto1('ninshou', '認証', 'にんしょう', 'To authenticate'),
      coto1('kaihatsu', '開発', 'かいはつ', 'To develop'),
      coto1('shori', '処理', 'しょり', 'To process (information)'),
      coto1('toukun', '–', 'トークン', 'Token'),
      coto1('taikenban', '体験版', 'たいけんばん', 'Trial version'),
      coto1('atai', '値', 'あたい', 'Value'),
      coto1('hensuu', '変数', 'へんすう', 'Variable'),
      coto1('kasou', '仮想', 'かそう', 'Virtual'),
      coto1('zeijakusei', '脆弱性', 'ぜいじゃくせい', 'Vulnerability'),
    ]),
  ];

  let allWords = [];
  output.forEach(set => {
    set.words.forEach(word => {
      allWords.push({ ...word }); // id value is overwritten by createSet
    });
  });

  return [
    createSet('Everything Combined', 'everything', allWords),
    ...output,
  ];

  // TODO: https://cotoacademy.com/japanese-it-vocabulary/

})();