const getWordBank = () => (() => {
  let nonUndef = (t) => { if (!t) throw new Error(); return t; };

  let m = (english, romaji, kana, kanji) => {
    return {
      EN: english,
      RO: romaji,
      KA: kana,
      KJ: nonUndef(kanji),
    };
  };

  let k = (kanji, romaji, kana, english) => m(nonUndef(english), romaji, kana, kanji);
  let coto1 = (romaji, kanji, kana, english) => m(nonUndef(english), romaji, kana, kanji);

  let createSet = (name, id, words) => {
    let idAlloc = 1;
    return {
      name,
      id,
      words: words.map(word => ({ ...word, id: id + ':' + idAlloc++ })),
    }
  };

  let output = [
    createSet('Daily Nouns', 'daily_nouns', [
      m('analysis', 'bunseki', 'ぶんせき', '分析'),
      m('effort, endeavor', 'doryoku', 'どりょく', '努力'),
      m('study; learning; tutorial', 'gakushuu', 'がくしゅう', '学習'),
      m('entry; filling in; filling out', 'kinyuu', 'きにゅう', '記入'),
      m('cooperation; collaboration', 'kyouryoku', 'きょうりょく', '協力'),
      m('growth; development; growing up; becoming an adult', 'seichou', 'せいちょう', '成長'),
      m('measuring ruler', 'jougi', 'じょうぎ', '定規'),
      k('集中','shuuchuu', 'しゅうちゅう', 'concentration; focusing; centralization; integration'),
      k('運転','unten','うんてん','operation; driving'),
      k('外出','gaishutsu','がいしゅつ','going out; outing; leaving'),
      k('博物館','hakubutsukan','はくぶつかん','museum'),
      k('会員',"kai'in", 'かいいん','member'),
      k('会計','kaikei','かいけい','finance; account; treasurer; bill'),
      k('権利','kenri','けんり','right; privilege'),
      k('記事','kiji','きじ','article; news story; report; account'),
      k('能力','nouryoku','のうりょく','ability; faculty'),
      k('入場','nyuujou','にゅうじょう','entrance; admission; entering'),
      k('連続','renzoku','れんぞく','continuation; succession; series'),
      k('作品','sakuhin','さくひん','work of art; performance'),
      k('資本','shihon','しほん','funds; capital'),
      k('集団','shuudan','しゅうだん','group; mass'),
      k('余分','yobun','よぶん','extra; excess; surplus'),
      m('correction tape', 'shuuseiteepo', 'しゅうせいテープ', '修正テープ'),
      m('correction fluid; white-out', 'shuuseieki', 'しゅうせいえき', '修正液'),
      m('pencil box', 'fudebako', 'ふでばこ', '筆箱'),
      m('pencil case', 'fudeire', 'ふでいれ', '筆入れ'),

    ]),
    createSet('IT words', 'it_words', [
      coto1('puroguramu', '–', 'プログラム', '(Computer) Program'),
      coto1('apuri', '–', 'アプリ', 'App'),
      coto1('burauza', '–', 'ブラウザ', 'Browser'),
      coto1('konpyuuta', '–', 'コンピュータ', 'Computer'),
      coto1('henkan', '変換', 'へんかん', 'Convert'),
      coto1('deita', '–', 'データ', 'Data'),
      coto1('desukutoppu', '–', 'デスクトップ', 'Desktop'),
      coto1('debaisu', '機器/デバイス', 'きき/デバイス', 'Device'),
      coto1('meiru', '–', 'メール', 'Email'),
      coto1('kakuchoushi', '拡張子', 'かくちょうし', 'File extension'),
      coto1('kansuu', '関数', 'かんすう', 'Function'),
      coto1('haadodoraibu', '–', 'ハードドライブ', 'Hard Drive'),
      coto1('haadouea', '–', 'ハードウエア', 'Hardware'),
      coto1('nyuuryoku', '入力', 'にゅうりょく', 'Input, to fill in'),
      coto1('intaanetto', '–', 'インターネット', 'Internet'),
      coto1('aipiadoresu', '–', 'IPアドレス', 'IP Address'),
      coto1('kiiboudo', '–', 'キーボード', 'Keyboard'),
      coto1('rapputoppu', '–', 'ラップトップ', 'Laptop'),
      coto1('kaisetsusho', '解説書', 'かいせつしょ', 'Manual'),
      coto1('monitaa', '–', 'モニター', 'Monitor'),
      coto1('mausu', '–', 'マウス', 'Mouse'),
      coto1('shutsuryoku', '出力', 'しゅつりょく', 'Output'),
      coto1('purintaa', '–', 'プリンター', 'Printer'),
      coto1('saikidou', '再起動', 'さいきどう', 'Restart'),
      coto1('uwagaki hozon', '(上書き) 保存', '(うわがき) ほぞん', 'Save'),
      coto1('gamen', '画面', 'がめん', 'Screen'),
      coto1('saabaa', '–', 'サーバー', 'Server'),
      coto1('settei', '設定', 'せってい', 'Settings'),
      coto1('supeisu/kuuhaku', 'スペース/空白', 'スペース/くうはく', 'Space'),
      coto1('kidou', '起動', 'きどう', 'Startup'),
      coto1('gijutsu', '技術', 'ぎじゅつ', 'Technology'),
      coto1('tanmatsu', '端末', 'たんまつ', 'Terminal'),
      coto1('tenpu', '添付', 'てんぷ', 'To attach'),
      coto1('asshuku', '圧縮', 'あっしゅく', 'To compress'),
      coto1('setsuzoku', '接続', 'せつぞく', 'To connect'),
      coto1('kopipe', '–', 'コピペ', 'To copy and paste'),
      coto1('kiritoru', '切り取る', 'きりとる', 'To cut'),
      coto1('kakidasu', '書き出す', 'かきだす', 'To export'),
      coto1('sounyuu', '挿入', 'そうにゅう', 'To insert'),
      coto1('haritsukeru', '貼り付ける', 'はりつける', 'To paste'),
      coto1('insatsu', '印刷', 'いんさつ', 'To print out'),
      coto1('kyouyuu', '共有', 'きょうゆう', 'To share'),
      coto1('kidou', '起動', 'きどう', 'To startup'),
      coto1('douki', '同期', 'どうき', 'To synchronize'),
      coto1('tacchipaddo', '–', 'タッチパッド', 'Touchpad'),
      coto1('uebusaito', '–', 'ウェブサイト', 'Website'),
    ]),
    createSet('Programming', 'programming', [
      coto1('', '追加', 'ついか', 'Add'),
      coto1('hiksuu', '引数', 'ひきすう', 'Argument, parameter'),
      coto1('hairetsu', '配列', 'はいれつ', 'Array'),
      coto1('jinkouchinou', '人工知能', 'じんこうちのう', 'Artificial intelligence, AI'),
      coto1('hidouki', '非同期', 'ひどうき', 'Asynchronous'),
      coto1('bakkendo', '–', 'バックエンド', 'Backend'),
      coto1('beitaban', 'ベータ版', 'ベータばん', 'Beta version'),
      coto1('bainari', '–', 'バイナリー', 'Binary'),
      coto1('nishinsuu', '二進数', 'にしんすう', 'Binary number'),
      coto1('bitto', '–', 'ビット', 'Bit'),
      coto1('buuru', '–', 'ブール', 'Boolean'),
      coto1('shingichi/shinrichi', '真偽値/真理値', 'しんぎち/しんりち', 'Boolean value'),
      coto1('bagu', '–', 'バグ', 'Bug'),
      coto1('birudo', '–', 'ビルド', 'Build (noun)'),
      coto1('kouru', '–', 'コール', 'Call'),
      coto1('moji', '文字', 'もじ', 'Character'),
      coto1('kurasu', '–', 'クラス', 'Class'),
      coto1('koudorebyuu', '–', 'コードレビュー', 'Code Review'),
      coto1('komandorain', '–', 'コマンドライン', 'Command Line'),
      coto1('konpairusuru', '–', 'コンパイルする', 'Compile'),
      coto1('sakusei', '作成', 'さくせい', 'Compose/create'),
      coto1('joukentsuki', '条件つき', 'じょうけんつき', 'Conditional'),
      coto1('teisuu', '定数', 'ていすう', 'Constant'),
      coto1('deitakouzou', 'データ構造', 'データこうぞう', 'Data Structure'),
      coto1('deitashurui', 'データ種類', 'データしゅるい', 'Data Type'),
      coto1('deitabeisu', '–', 'データベース', 'Database'),
      coto1('debaggu', '–', 'デバッグ', 'Debug'),
      coto1('debaggusuru', '–', 'デバッグする', 'Debugging'),
      coto1('sengen', '宣言', 'せんげん', 'Declaration'),
      coto1('fukugou', '復号', 'ふくごう', 'Decryption'),
      coto1('teigi', '定義', 'ていぎ', 'Define'),
      coto1('nouhin', '納品', 'のうひん', 'Delivery'),
      coto1('haibi', '配備', 'はいび', 'Deploy'),
      coto1('sekkei', '設計', 'せっけい', 'Design/architecture'),
      coto1('kaihatsusha', '開発者', 'かいはつしゃ', 'Developer'),
      coto1('kaihatsu', '開発', 'かいはつ', 'Development'),
      coto1('kaihatsukankyou', '開発環境', 'かいはつかんきょう', 'Development environment'),
      coto1('douteki', '動的', 'どうてき', 'Dynamic'),
      coto1('angouka', '暗号化', 'あんごうか', 'Encryption'),
      coto1('eraa', '–', 'エラー', 'Error'),
      coto1('ibento', '–', 'イベント', 'Event'),
      coto1('ibentohandoraa', '–', 'イベントハンドラー', 'Event Handler'),
      coto1('reigai', '例外', 'れいがい', 'Exception'),
      coto1('fureimuwaaku', '–', 'フレームワーク', 'Framework'),
      coto1('furontoendo', '–', 'フロントエンド', 'Front End'),
      coto1('furusutakku', '–', 'フルスタック', 'Full Stack'),
      coto1('kinou', '機能', 'きのう', 'Function'),
      coto1('kansuu', '関数 ', 'かんすう', 'Function'),
      coto1('HTTP rikuesuto', '–', 'HTTPリクエスト', 'HTTP Request'),
      coto1('jissou', '実装', 'じっそう', 'Implementation'),
      coto1('nyuuryoku', '入力', 'にゅうりょく', 'Input'),
      coto1('seisuu (gata)', '整数 (型)', 'せいすう (がた)', 'Integer (type)'),
      coto1('ruupu', '–', 'ループ', 'Loop'),
      coto1('kikaigakushuu', '機械学習', 'きかいがくしゅう', 'Machine Learning'),
      coto1('hoshu', '保守', 'ほしゅ', 'Maintenance'),
      coto1('kanri', '管理', 'かんり', 'Manage'),
      coto1('nyuurarunettowaaku', '–', 'ニューラルネットワーク', 'Neural Network'),
      coto1('nuru', '–', 'ヌル', 'Null'),
      coto1('obujekuto', '–', 'オブジェクト', 'Object'),
      coto1('obujekutoshikou', 'オブジェクト指向', 'オブジェクトしこう', 'Object-oriented'),
      coto1('unyou', '運用', 'うんよう', 'Operation'),
      coto1('enzanshi', '演算子', 'えんざんし', 'Operator'),
      coto1('autoputto', '–', 'アウトプット', 'Output'),
      coto1('heiretsushori', '並列処理', 'へいれつしょり', 'Parallel processing'),
      coto1('parameita', '–', 'パラメータ', 'Parameter'),
      coto1('pursesu/shori', 'プロセス/処理', 'プロセス/しょり', 'Process'),
      coto1('puroguramingu', '–', 'プログラミング', 'Programming'),
      coto1('konpyuutaagengo', 'コンピューター言語', 'コンピューターげんご', 'Programming language'),
      coto1('gijiransuu', '擬似乱数', 'ぎじらんすう', 'Pseudo-random number'),
      coto1('ransuu', '乱数', 'らんすう', 'Random number'),
      coto1('shouchousei', '冗長性', 'じょうちょうせい', 'Redundancy'),
      coto1('jikkou', '実行 ', 'じっこう', 'Run/execute'),
      coto1('sekyuritii', '–', 'セキュリティー', 'Security'),
      coto1('sofutouea', '–', 'ソフトウェア', 'Software'),
      coto1('sousu', '–', 'ソース', 'Source'),
      coto1('shou', '仕様', 'しよう', 'Specification'),
      coto1('supurinto', '–', 'スプリント', 'Sprint'),
      coto1('suteitomento', '–', 'ステートメント', 'Statement'),
      coto1('seiteki', '静的', 'せいてき', 'Static'),
      coto1('teishi', '停止', 'ていし', 'Stop'),
      coto1('kijiretsu', '文字列', 'もじれつ', 'String'),
      coto1('kouzou', '構造', 'こうぞう', 'Structure'),
      coto1('tagu', '–', 'タグ', 'Tag'),
      coto1('tesuto', '–', 'テスト', 'Test'),
      coto1('ninshou', '認証', 'にんしょう', 'To authenticate'),
      coto1('kaihatsu', '開発', 'かいはつ', 'To develop'),
      coto1('shori', '処理', 'しょり', 'To process (information)'),
      coto1('toukun', '–', 'トークン', 'Token'),
      coto1('taikenban', '体験版', 'たいけんばん', 'Trial version'),
      coto1('atai', '値', 'あたい', 'Value'),
      coto1('hensuu', '変数', 'へんすう', 'Variable'),
      coto1('kasou', '仮想', 'かそう', 'Virtual'),
      coto1('zeijakusei', '脆弱性', 'ぜいじゃくせい', 'Vulnerability'),
    ]),
    createSet('Body Parts', 'body', [
      m('organ (of body, plant, etc.)','kikan','きかん','器官'),
      m('brain','nou','のう','脳'),
      m('heart','shinzou','しんぞう','心臓'),
      m('liver','kanzou','かんぞう','肝臓'),
      m('kidney','jinzou','じんぞう','腎臓'),
      m('lung','hai','はい','肺'),
      m('stomach','i','い','胃'),
      m('guts; bowels; intestines','chou','ちょう','腸'),
      m('large intestine; large bowel; colon','daichou','だいちょう','大腸'),
      m('small intestine','shouchou','しょうちょう','小腸'),
      m('appendix','mouchou','もうちょう','盲腸'),
      m('rectum','chokuchou','ちょくちょう','直腸'),
      m('pancreas','suizou','すいぞう','膵臓'),
      m('spleen','hizou','ひぞう','脾臓'),
      m('gall bladder','tannou','たんのう','胆嚢'),
      m('lymph node','rinpasetsu','りんぱせつ','淋巴節'),
      m('urinary bladder','boukou','ぼうこう','膀胱'),
      m('skin','hifu','ひふ','皮膚'),
      m('blood','ketsueki','けつえき','血液'),
      m('blood','chi','ち','血'),
      m('blood vessel; vein','kekkan','けっかん','血管'),
      m('vein','jyoumyaku','じょうみゃく','静脈'),
      m('artery','doumyaku','どうみゃく','動脈'),
      m('muscle','kinniku','きんにく','筋肉'),
      m('bone','hone','ほね','骨'),
      m('bone marrow; medulla','kotsusui','こつずい','骨髄'),
      m('skeleton; skeletal structure; build; frame; physique','kokkaku','こっかく','骨格'),
      m('spine; backbone; spinal column','sehone','せぼね','背骨'),
      m('head','atama','あたま','頭'),
      m('forehead; brow','hitai','ひたい','額'),
      m('hair (on the head)','kaminoke','かみのけ','髪の毛'),
      m('neck','kubi','くび','首'),
      m('face','kao','かお','顔'),
      m('eye; eyes','me','め','目'),
      m('eye; pupil of the eye','hitomi','ひとみ','瞳'),
      m('eyebrow; eyebrows','mayu','まゆ','眉'),
      m('eyelashes','matsuge','まつげ','睫毛'),
      m('cheek','hoo','ほお','頬'),
      m('mouth','kuchi','くち','口'),
      m('lips','kuchibiru','くちびる','唇'),
      m('tongue','shita','した','舌'),
      m('tooth; teeth','ha','は','歯'),
      m('ear','mimi','みみ','耳'),
      m('nose','hana','はな','鼻'),
      m('arm','ude','うで','腕'),
      m('chin, jaw','ago','あご','顎'),
      m('moustache; beard','hige','ひげ','髭'),
      m('throat','nodo','のど','喉'),
      m('shoulder','kata','かた','肩'),
      m('hand','te','て','手'),
      m('elbow','hiji','ひじ','肘'),
      m('wrist','tekubi','てくび','手首'),
      m('finger','yubi','ゆび','指'),
      m('Index finger','hitosashiyubi','ひとさしゆび','人差し指'),
      m('Thumb','oyayubi','おやゆび','親指'),
      m('Middle finger; long finger; second finger; tall finger; middle toe; third toe','nakayubi','なかゆび','中指'),
      m('Ring finger; fourth finger','kusuriyubi','くすりゆび','薬指'),
      m('Little finger; pinky OR Little toe','koyubi','こゆび','小指'),
      m('nail (as in fingernail and toenail)','tsume','つめ','爪'),
      m('chest; breast','mune','むね','胸'),
      m('mind; heart; spirit','kokoro','こころ','心'),
      m('breast; nipple','chibusa','ちぶさ','乳房'),
      m('nipple; teat','chikubi','ちくび','乳首'),
      m('stomach','onaka','おなか','お腹'),
      m('abdomen; belly; stomach','hara','はら','腹'),
      m('naval; belly button','heso','へそ','臍'),
      m('back; spine','se','せ','背'),
      m('back of the body','senaka','せなか','背中'),
      m('back; lower back; waist; hips','koshi','こし','腰'),
      m('hips','youkan','ようかん','腰間'),
      m('hips; buttocks; backside','hippu','ヒップ','ヒップ'),
      m('buttocks; bottom','shiri','しり','尻'),
      m('thigh','momo','もも','股'),
      m('knee','hiza','ひざ','膝'),
      m('foot; leg','ashi','あし','足'),
      m('ankle','ashikubi','あしくび','足首'),
      m('heel','kakato','かかと','踵'),
      m('heel','heeru','ヒール','ヒール'),
      m('toes; tips of the toes','tsumasaki','つまさき','つま先'),
    ]),
    createSet('Professions', 'professions', [
      m('cook; chef', 'ryouriin', 'りょうりにん', '料理人'),
      m('nurse; registered nurse', 'kangoshi', 'かんごし', '看護師'),
      m('trader; shopkeeper; merchant', 'shounin', 'しょうにん', '商人'),
      m('shopkeeper', 'tenshu', 'てんしゅ', '店主'),
      m('butcher', 'nikuya', 'にくや', '肉屋'),
      m('fish market; fish dealer; fishmonger', 'sakanaya', 'さかなや', '魚屋'),
      m('Photographer', 'shashinka', 'しゃしんか', '写真家'),
      m('cameraman; photographer; cinematographer', 'kameraman', 'カメラマン', 'カメラマン'),
      m('painter; artist', 'gaka', 'がか', '画家'),
      m('driver; train driver; train engineer; motorman; taxi driver', 'untenshi', 'うんてんし', '運転士'),
      m('singer', 'kashuu', 'かしゅ', '歌手'),
      m('composer', 'sakkyokuka', 'さっきょくか', '作曲家'),
      m('programmer', 'puroguramaa', 'プログラマー', 'プログラマー'),
      m('engineer; technical expert; technician; craftsperson', 'gijutsusha', 'ぎじゅつしゃ', '技術者'),
      m('engineer', 'enjinia', 'エンジニア', 'エンジニア'),
      m('pilot', 'kichou', 'きちょう', '機長'),
      m('pilot', 'pairotto', 'パイロット', 'パイロット'),
      m('occupation; business', 'shokugyou', 'しょくぎょう', '職業'),
      m('teacher; instructor; teaching staff; faculty member', 'kyouin', 'きょういん', '教員'),
      m('fireman; firefighter', 'shouboushi', 'しょうぼうし', '消防士'),
      m('banker; bank proprietor; bank manager', 'ginkouka', 'ぎんこうか', '銀行家'),
      m('author; writer; novelist; artist', 'sakka', 'さっか', '作家'),
      m('scientist', 'kagakusha', 'かがくしゃ', '科学者'),
      m('researcher', 'kenkyuusha', 'けんきゅうしゃ', '研究者'),
    ]),
    createSet('Animals', 'animals', [
      m('zebra','shimauma','しまうま','縞馬'),
      m('zebra','zebura','ゼブラ','ゼブラ'),
      m('moose, elk','herajika','へらじか','箆鹿'),
      m('large deer, moose, elk','oojika','おおじか','大鹿'),
      m('moose','muusu','ムース','ムース'),
      m('lion','raion','ライオン','ライオン'),
      m('chimpanzee','chinpanji','チンパンジー','チンパンジー'),
      m('chimpanzee','kuroshoujyou','くろしょうじょう','黒猩々'),
      m('orangutan','shoujyou','しょうじょう','猩々'),
      m('gorilla','gorira','ゴリラ','ゴリラ'),
      m('tortoise','kame','かめ','亀'),
      m('kangaroo','kangaruu','カンガルー','カンガルー'),
      m('peacock','kujyaku','くじゃく','孔雀'),
      m('camel','rakuda','らくだ','駱駝'),
      m('sheep','hitsuji','ひつじ','羊'),
      m('goat','yagi','やぎ','山羊'),
      m('hippopotamus','kaba','かば','河馬'),
      m('giraffe','kirin','キリン','麒麟'),
      m('mouse; rat','nezumi','ねずみ','鼠'),
      m('monkey','saru','さる','猿'),
      m('elephant','zou','ぞう','象'),
      m('snake','hebi','へび','蛇'),
      m('tiger','tora','とら','虎'),
      m('deer','shika','しか','鹿'),
      m('pig','buta','ぶた','豚'),
      m('cow','ushi','うし','牛'),
      m('chicken','niwatori','にわとり','鶏'),
      m('horse','uma','うま','馬'),
      m('insect; bug; cricket; moth; worm','mushi','むし','虫'),
      m('insect; bug','konchuu','こんちゅう','昆虫'),
      m('ant','ari','あり','蟻'),
      m('termite; white ant','shiroari','しろあり','白蟻'),
      m('cockroach','gokiburi','ごきぶり','蜚蠊'),
      m('ladybug','tentou mushi','てんとうむし','てんとう虫'),
      m('bee; wasp; hornet','hachi','はち','蜂'),
      m('firefly','hotaru','ほたる','蛍'),
      m('rhinoceros beetle','kabutomushi','かぶとむし','甲虫'),
      m('dragonfly','tonbo','とんぼ','蜻蛉'),
      m('grasshopper','batta','ばった','飛蝗'),
      m('butterfly','chou','ちょう','蝶'),
      m('hornworm (caterpillar of a hawk moth); (hairless) caterpillar','imo mushi','いもむし','芋虫'),
      m('caterpillar, esp. hairless','hadaka mushi','はだかむし','裸虫'),
      m('hairy caterpillar','kemushi','けむし','毛虫'),
      m('aphid','aburamushi','あぶらむし','油虫'),
      m('cricket','koorogi','こおろぎ','蟋蟀'),
      m('cicada','semi','せみ','蝉'),
      m('spider','kumo','くも','蜘蛛'),
      m('mosquito','ka','か','蚊'),
      m('worm; insect','mushikera','むしけら','虫螻'),
      m('roundworm','kaichuu','かいちゅう','回虫'),
      m('earthworm','mimizu','みみず','蚯蚓'),
      m('centipede','mukade','むかで','百足'),
      m('millipede','yasude','やすで','馬陸'),
      m('fly','hae','はえ','蝿'),
      m('moth','ga','が','蛾'),
      m('fruit fly','shoijyoi hae','しょうじょうばえ','猩猩蠅'),
      m('maggot','ujimushi','うじむし','蛆虫'),
      m('water strider','amenbo','あめんぼ','水黽'),
      m('shark', 'same', 'さめ', '鮫'),
      m('shellfish','kairui','かいるい','貝類'),
      m('shell; shellfish','kai','かい','貝'),
      m('marine products; seafood; fish and shellfish','gyokairui','ぎょかいるい','魚介類'),
      m('Tuna','maguro','まぐろ','鮪'),
      m('young Japanese amberjack; young yellowtail','hamachi','はまち','魬'),
      m('mackerel','saba','さば','鯖'),
      m('sea bream','tai','たい','鯛'),
      m('stingray','ei','えい','海鷂魚'),
      m('jellyfish','kurage','くらげ','海月'),
      m('sea cucumber','namako','なまこ','海鼠'),
      m('walrus','kaiba','かいば','海馬'),
      m('seahorse; sea horse','tatsu no oto shigo','たつのおとしご','竜の落し子'),
      m('true seal','azarashi','あざらし','海豹'),
      m('sea lion','ashika','あしか','海驢'),
      m('whale','kujira','くじら','鯨'),
      m('dolphin, porpoises, belugas, etc.','iruka','いるか','海豚'),
      m('dolphin','dorufin','ドルフィン','ドルフィン'),
      m('salmon','sake','さけ','鮭'),
      m('trout; sea trout','masu','ます','鱒'),
      m('octopus','tako','たこ','蛸'),
      m('sea otter','rakko','らっこ','海獺'),
      m('eel (esp Japanese eel)','unagi','うなぎ','鰻'),
      m('catfish','namazu','なまず','鯰'),
      m('tai, species of red Pacific sea bream','madai','まだい','真鯛'),
      m('spiny lobster','ise\'ebi','いせえび','伊勢海老'),
      m('puffer fish','fugu','ふぐ','河豚'),
      m('swordfish','mekajiki','めかじき','眼梶木'),
      m('marlin; swordfish; spearfish; sailfish','kajiki','かじき','梶木'),
      m('sea urchin; sea urchin eggs','uni','うに','雲丹'),
      m('abalone','awabi','あわび','鮑'),
      m('cod; haddock','tara','たら','鱈'),
      m('oyster','kaki','かき','牡蠣'),
      m('penguin','pengin','ペンギン','ペンギン'),
      m('walrus','seiuchi','せいうち','海象'),
      m('polar bear','hokkyokuguma','ほっきょくぐま','北極熊'),
    ]),
  ];

      // m('ENGLISH', 'ROMAJI', 'KANA', 'KANJI'),

  let allWords = [];
  output.forEach(set => {
    set.words.forEach(word => {
      allWords.push({ ...word }); // id value is overwritten by createSet
    });
  });

  return [
    createSet('Everything Combined', 'everything', allWords),
    ...output,
  ];

  // TODO: https://cotoacademy.com/japanese-it-vocabulary/

})();