const getWordBank = () => (() => {
  let nonUndef = (t) => { if (!t) throw new Error(); return t; };

  let m = (english, romaji, kana, kanji) => {
    return {
      EN: english,
      RO: romaji,
      KA: kana,
      KJ: nonUndef(kanji),
    };
  };

  let k = (kanji, romaji, kana, english) => m(nonUndef(english), romaji, kana, kanji);
  let coto1 = (romaji, kanji, kana, english) => m(nonUndef(english), romaji, kana, kanji);

  let createSet = (name, id, words) => {
    let idAlloc = 1;
    return {
      name,
      id,
      words: words.map(word => ({ ...word, id: id + ':' + idAlloc++ })),
    }
  };

  let output = [
    createSet('Daily Nouns', 'daily_nouns', [
      m('analysis', 'bunseki', 'ぶんせき', '分析'),
      m('effort, endeavor', 'doryoku', 'どりょく', '努力'),
      m('study; learning; tutorial', 'gakushuu', 'がくしゅう', '学習'),
      m('entry; filling in; filling out', 'kinyuu', 'きにゅう', '記入'),
      m('cooperation; collaboration', 'kyouryoku', 'きょうりょく', '協力'),
      m('growth; development; growing up; becoming an adult', 'seichou', 'せいちょう', '成長'),
      m('measuring ruler', 'jougi', 'じょうぎ', '定規'),
      k('集中','shuuchuu', 'しゅうちゅう', 'concentration; focusing; centralization; integration'),
      k('運転','unten','うんてん','operation; driving'),
      k('外出','gaishutsu','がいしゅつ','going out; outing; leaving'),
      k('博物館','hakubutsukan','はくぶつかん','museum'),
      k('会員',"kai'in", 'かいいん','member'),
      k('会計','kaikei','かいけい','finance; account; treasurer; bill'),
      k('権利','kenri','けんり','right; privilege'),
      k('記事','kiji','きじ','article; news story; report; account'),
      k('能力','nouryoku','のうりょく','ability; faculty'),
      k('入場','nyuujou','にゅうじょう','entrance; admission; entering'),
      k('連続','renzoku','れんぞく','continuation; succession; series'),
      k('作品','sakuhin','さくひん','work of art; performance'),
      k('資本','shihon','しほん','funds; capital'),
      k('集団','shuudan','しゅうだん','group; mass'),
      k('余分','yobun','よぶん','extra; excess; surplus'),
      m('correction tape', 'shuuseiteepo', 'しゅうせいテープ', '修正テープ'),
      m('correction fluid; white-out', 'shuuseieki', 'しゅうせいえき', '修正液'),
      m('pencil box', 'fudebako', 'ふでばこ', '筆箱'),
      m('pencil case', 'fudeire', 'ふでいれ', '筆入れ'),
    ]),

    createSet('Adjectives', 'adjectives', [
      m('Lively / Bustling / Busy', 'nigiyaka', 'にぎやか', '賑やか'),
      m('Quiet', 'shizuka', 'しずか', '静か'),
      m('Beautiful / Clean', 'kirei', 'きれい (*)', '奇麗'),
      m('Like / Love / Favorite', 'suki', 'すき', '好き'),
      m('Dislike / Hate / Least Favorite', 'kirai', 'きらい (*)', '嫌い'),
      m('Strong / Robust / Healthy', 'joubu', 'じょうぶ', '丈夫'),
      m('Various', 'iroiro', 'いろいろ', '色々'),
      m('Kind', 'shinsetsu', 'しんせつ', '親切'),
      m('Healthy / Vigorous / Energetic', 'genki', 'げんき', '元気'),
      m('Convenient', 'benri', 'べんり', '便利'),
      m('Simple / Easy', 'kantan', 'かんたん', '簡単'),
      m('Complicated', 'fukuzatsu', 'ふくざつ', '複雑'),
      m('Free (time)', 'hima', 'ひま', '暇'),
      m('Skillfull / Good at', 'jouzu', 'じょうず', '上手'),
      m('Unskillful / Poor at', 'heta', 'へた', '下手'),
      m('Fresh', 'shinsen', 'しんせん', '新鮮'),
      m('Wonderful / Lovely / Cool', 'suteki', 'すてき', '素敵'),
      m('All Right / No Problem', 'daijoubu', 'だいじょうぶ', '大丈夫'),
      m('Polite', 'teinei', 'ていねい', '丁寧'),
      m('Famous', 'yuumei', 'ゆうめい (*)', '有名'),
      m('Strange / Odd', 'hen', 'へん', '変'),
      m('Regrettable / Sorry / Pity', 'zannen', 'ざんねん', '残念'),
      m('Safe', 'anzen', 'あんぜん', '安全'),
      m('New', 'atarashii', 'あたらしい', '新しい'),
      m('Old', 'furui', 'ふるい', '古い'),
      m('Thick (books)', 'atsui', 'あつい', '厚い'),
      m('Thin', 'usui', 'うすい', '薄い'),
      m('Hot (weather)', 'atsui', 'あつい', '暑い'),
      m('Cold / Chilly (weather)', 'samui', 'さむい', '寒い'),
      m('Warm (weather)', 'atatakai', 'あたたかい', '暖かい'),
      m('Cool (weather)', 'suzushii', 'すずしい', '涼しい'),
      m('Hot (drink)', 'atsui', 'あつい', '熱い'),
      m('Cold (drink)', 'tsumetai', 'つめたい', '冷たい'),
      m('Warm (drink)', 'atatakai', 'あたたかい', '温かい'),
      m('Big', 'ookii', 'おおきい', '大きい'),
      m('Small', 'chiisai', 'ちいさい', '小さい'),
      m('Heavy', 'omoi', 'おもい', '重い'),
      m('Light (weight)', 'karui', 'かるい', '軽い'),
      m('Interesting', 'omoshiroi', 'おもしろい', '面白い'),
      m('Dull / Boring', 'tsumaranai', 'つまらない', '詰まらない'),
      m('Wide', 'hiroi', 'ひろい', '広い'),
      m('Narrow', 'semai', 'せまい', '狭い'),
      m('High / Tall (height)', 'takai', 'たかい', '高い'),
      m('Low / Short (height)', 'hikui', 'ひくい', '低い'),
      m('Expensive', 'takai', 'たかい', '高い'),
      m('Cheap', 'yasui', 'やすい', '安い'),
      m('Long (length)', 'nagai', 'ながい', '長い'),
      m('Short (length)', 'mijikai', 'みじかい', '短い'),
      m('Fat/Thick', 'futoi', 'ふとい', '太い'),
      m('Thin / Slender / Narrow', 'hosoi', 'ほそい', '細い'),
      m('Tasty', 'oishii', 'おいしい', '美味しい'),
      m('Unappetizing / Tasteless', 'mazui', 'まずい', '不味い'),
      m('Difficult', 'muzukashii', 'むずかしい', '難しい'),
      m('Easy / Simple', 'yasashii', 'やさしい', '易しい'),
      m('Good / Nice / OK / Prefer', 'ii / yoi', 'いい / よい', '良い'),
      m('Bad / Wicked', 'warui', 'わるい', '悪い'),
      m('Cute / Pretty', 'kawaii', 'かわいい', '可愛い'),
      m('Red', 'akai', 'あかい', '赤い'),
      m('Blue', 'aoi', 'あおい', '青い'),
      m('White', 'shiroi', 'しろい', '白い'),
      m('Black', 'kuroi', 'くろい', '黒い'),
      m('Round', 'marui', 'まるい', '丸い'),
      m('Sweet', 'amai', 'あまい', '甘い'),
      m('Hot / Spicy (taste)', 'karai', 'からい', '辛い'),
      m('Hard', 'katai', 'かたい', '固い'),
      m('Soft', 'yawarakai', 'やわらかい', '柔らかい'),
      m('Near', 'chikai', 'ちかい', '近い'),
      m('Far', 'tooi', 'とおい', '遠い'),
      m('Early', 'hayai', 'はやい', '早い'),
      m('Fast / Quick', 'hayai', 'はやい', '速い'),
      m('Late / Slow', 'osoi', 'おそい', '遅い'),
      m('Bright / Light', 'akarui', 'あかるい', '明るい'),
      m('Dark / Gloomy', 'kurai', 'くらい', '暗い'),
      m('Busy', 'isogashii', 'いそがしい', '忙しい'),
      m('Enjoyable / Fun', 'tanoshii', 'たのしい', '楽しい'),
      m('Many / Plenty', 'ooi', 'おおい', '多い'),
      m('Few / Little', 'sukunai', 'すくない', '少ない'),
      m('Dirty', 'kitanai', 'きたない', '汚い'),
      m('Sleepy', 'nemui', 'ねむい', '眠い'),
      m('Young', 'wakai', 'わかい', '若い'),
      m('Strong / Tough', 'tsuyoi', 'つよい', '強い'),
      m('Weak', 'yowai', 'よわい', '弱い'),
      m('Painful', 'itai', 'いたい', '痛い'),
      m('Dangerous', 'abunai', 'あぶない', '危ない'),
      m('Correct / Right', 'tadashii', 'ただしい', '正しい'),
    ]),

    createSet('Around the home', 'around_home', [
      m('Bedroom', 'shin shitsu', 'しんしつ', '寝室'),
      m('Bedroom', 'beddo ru-mu', 'ベッドルーム', 'ベッドルーム'),
      m('Dining Room', 'dainingu ru-mu', 'ダイニングルーム', 'ダイニングルーム'),
      m('Living Room (Western Style)', 'ima', 'いま', '居間'),
      m('Living Room', 'ribingu ru-mu', 'リビングルーム', 'リビングルーム'),
      m('Kitchen', 'dai dokoro', 'だいどころ', '台所'),
      m('Kitchen', 'kicchin', 'キッチン', 'キッチン'),
      m('Kitchen Utensil / Kitchenware', 'dai dokoro youhin', 'だいどころようひん', '台所用品'),
      m('Garage', 'shako', 'しゃこ', '車庫'),
      m('Cupboard / Cabinet', 'todana', 'とだな', '戸棚'),
      m('Faucet / Tap', 'jaguchi', 'じゃぐち', '蛇口'),
      m('Kitchen Sink', 'nagashi', 'ながし', '流し'),
      m('Washbasin / Washstand', 'senmen dai', 'せんめんだい', '洗面台'),
      m('Bathroom', 'furoba', 'ふろば', '風呂場'),
      m('Bathroom', 'basu ru-mu', 'バスルーム', 'バスルーム'),
      m('Entrance / Hallway / Front Door', 'genkan', 'げんかん', '玄関'),
      m('Garden / Yard', 'niwa', 'にわ', '庭'),
      m('Balcony', 'beranda', 'ベランダ', 'ベランダ'),
      m('Corridor', 'rouka', 'ろうか', '廊下'),
      m('Stairs / Staircase', 'kaidan', 'かいだん', '階段'),
      m('Floor', 'yuka', 'ゆか', '床'),
      m('Mat / Japanese Straw Floor Coverings', 'tatami', 'たたみ', '畳'),
      m('Wall', 'kabe', 'かべ', '壁'),
      m('Key', 'kagi', 'かぎ', '鍵'),
      m('Window', 'mado', 'まど', '窓'),
      m('Curtain', 'ka-ten', 'カーテン', 'カーテン'),
      m('Ceiling', 'tenjou', 'てんじょう', '天井'),
      m('Furniture', 'kagu', 'かぐ', '家具'),
      m('Closet', 'oshiire', 'おしいれ', '押入れ'),
      m('Wardrobe / Chest of Drawers', 'tansu', 'たんす', '箪笥'),
      m('Mirror', 'kagami', 'かがみ', '鏡'),
      m('Table', 'te-buru', 'テーブル', 'テーブル'),
      m('Chair', 'isu', 'いす', '椅子'),
      m('Sofa / Couch', 'sofa-', 'ソファー', 'ソファー'),
      m('Desk', 'tsukue', 'つくえ', '机'),
      m('Carpet', 'jyuutan', 'じゅうたん', '絨毯 / 絨緞'),
      m('Bookshelf', 'hondana', 'ほんだな', '本棚'),
      m('Table Lamp', 'sutando', 'スタンド', 'スタンド'),
      m('Bed', 'beddo', 'ベッド', 'ベッド'),
      m('Japanese-style Bedding', 'futon', 'ふとん', '布団'),
      m('Sheet / Bedsheet', 'shi-tsu', 'シーツ', 'シーツ'),
      m('Blanket', 'moufu', 'もうふ', '毛布'),
      m('Pillow', 'makura', 'まくら', '枕'),
      m('Umbrella Stand', 'kasatate', 'かさたて', '傘立て'),
      m('Refrigerator', 'reizouko', 'れいぞうこ', '冷蔵庫'),
      m('Freezer', 'reitouko', 'れいとうこ', '冷凍庫'),
      m('Washing Machine', 'sentaku ki', 'せんたくき', '洗濯機'),
      m('Drying Machine', 'kansou ki', 'かんそうき', '乾燥機'),
      m('Clothes-pin / Peg', 'sentaku basami', 'せんたくばさみ', '洗濯挟み'),
      m('Clothes Hanger', 'hanga-', 'ハンガー', 'ハンガー'),
      m('Laundry Pole (for drying)', 'mono hoshi zao', 'ものほしざお', '物干し竿'),
      m('Electric Vacuum Cleaner', 'denki souji ki', 'でんきそうじき', '電気掃除機'),
      m('Dishwasher', 'sara arai ki', 'さらあらいき', '皿洗い機'),
      m('(Electric) Iron', 'airon', 'アイロン', 'アイロン'),
      m('Ironing Board', 'airon dai', 'アイロンだい', 'アイロン台'),
      m('Air-conditioner', 'eakon', 'エアコン', 'エアコン'),
      m('Electric Fan', 'senpuu ki', 'せんぷうき', '扇風機'),
      m('Electricity / (Electric) Light', 'denki', 'でんき', '電気'),
      m('Electric Light', 'dentou', 'でんとう', '電灯'),
      m('Microwave Oven', 'denshi renji', 'でんしレンジ', '電子レンジ'),
      m('Oven', 'o-bun', 'オーブン', 'オーブン'),
      m('Stove / Heater', 'suto-bu', 'ストーブ', 'ストーブ'),
      m('Plate', 'osara', 'おさら', 'お皿'),
      m('Glass', 'koppu', 'コップ', 'コップ'),
      m('Cup', 'kappu', 'カップ', 'カップ'),
      m('Broom', 'houki', 'ほうき', '箒'),
      m('Dustpan', 'chiri tori', 'ちりとり', '塵取り'),
      m('Rubbish Bin / Gabbage Box', 'gomi bako', 'ごみばこ', 'ごみ箱'),
      m('Japanese-style room', 'washitsu', 'わしつ', '和室'),
      m('Shoji (Paper sliding door)', 'shouji', 'しょうじ', '障子'),
      m('Veranda / Porch / Balcony', 'engawa', 'えんがわ', '縁側'),
      m('Dirt floor / Room with dirt floor', 'doma', 'どま', '土間'),
      m('warehouse / storehouse', 'kura', 'くら', '蔵 / 倉 / 庫'),
    ]),

    createSet('Education/Academia', 'edu', [
      m('Kindergarten', 'youchi en', 'ようちえん', '幼稚園'),
      m('Primary School / Elementary School', 'shou gakkou', 'しょうがっこう', '小学校'),
      m('Secondary School / Junior High School', 'chuu gakkou', 'ちゅうがっこう', '中学校'),
      m('Senior High School', 'koutou gakkou', 'こうとうがっこう', '高等学校'),
      m('Senior High School', 'koukou', 'こうこう', '高校'),
      m('Graduate School', 'daigaku in', 'だいがくいん', '大学院'),
      m('Public School', 'kouritsu gakkou', 'こうりつがっこう', '公立学校'),
      m('Private School', 'shiritsu gakkou', 'しりつがっこう', '私立学校'),
      m('Night School', 'ya gakkou', 'やがっこう', '夜学校'),
      m('Cram School', 'juku', 'じゅく', '塾'),
      m('National Language (Japanese)', 'kokugo', 'こくご', '国語'),
      m('Science', 'kagaku', 'かがく', '科学'),
      m('Chemistry', 'kagaku', 'かがく', '化学'),
      m('Mathematics', 'suugaku', 'すうがく', '数学'),
      m('Physics', 'butsuri', 'ぶつり', '物理'),
      m('Biology', 'seibutsu gaku', 'せいぶつがく', '生物学'),
      m('Art', 'bijutsu', 'びじゅつ', '美術'),
      m('Physical Education', 'taiiku', 'たいいく', '体育'),
      m('History', 'rekishi', 'れきし', '歴史'),
      m('Geography', 'chiri', 'ちり', '地理'),
      m('Economics', 'keizai', 'けいざい', '経済'),
      m('Literature', 'bun gaku', 'ぶんがく', '文学'),
      m('Music', 'on gaku', 'おんがく', '音楽'),
      m('Engineering', 'kou gaku', 'こうがく', '工学'),
      m('Medicine', 'i gaku', 'いがく', '医学'),
      m('Architecture', 'kenchiku gaku', 'けんちくがく', '建築学'),
      m('Accounting', 'kaikei gaku', 'かいけいがく', '会計学'),
      m('Philosophy', 'tetsu gaku', 'てつがく', '哲学'),
      m('Law', 'hou gaku', 'ほうがく', '法学'),
      m('Major Subject', 'senkou', 'せんこう', '専攻'),
      m('Hostel / Dormitory', 'ryou', 'りょう', '寮'),
      m('Dormitory / Boading House', 'kishuku sha', 'きしゅくしゃ', '寄宿舎'),
      m('Library', 'tosho kan', 'としょかん', '図書館'),
      m('Gymnasium', 'taiiku kan', 'たいいくかん', '体育館'),
      m('Classroom', 'kyou shitsu', 'きょうしつ', '教室'),
      m('Office', 'jimu shitsu', 'じむしつ', '事務室'),
      m('Laboratory', 'jikken shitsu', 'じっけんしつ', '実験室'),
      m('Principal', 'kouchou', 'こうちょう', '校長'),
      m('Vice Principal', 'kyoutou', 'きょうとう', '教頭'),
      m('Teacher', 'sensei', 'せんせい', '先生'),
      m('Teacher', 'kyoushi', 'きょうし', '教師'),
      m('Student', 'gakusei', 'がくせい', '学生'),
      m('Oversea Student', 'ryuu gakusei', 'りゅうがくせい', '留学生'),
      m('Classmate', 'dou kyuu sei', 'どうきゅうせい', '同級生'),
      m('Classmate', 'kurasume-to', 'クラスメート', 'クラスメート'),
      m('Compulsory Education', 'gimu kyouiku', 'ぎむきょういく', '義務教育'),
      m('Uniform', 'seifuku', 'せいふく', '制服'),
      m('Entry to School / Admission to School', 'nyuu gaku', 'にゅうがく', '入学'),
      m('Graduation', 'sotsugyou', 'そつぎょう', '卒業'),
      m('Examination / Test', 'shiken', 'しけん', '試験'),
      m('Test', 'tesuto', 'テスト', 'テスト'),
      m('Midterm Examination', 'chuukan shiken', 'ちゅうかんしけん', '中間試験'),
      m('Final Examination', 'kimatsu shiken', 'きまつしけん', '期末試験'),
      m('Sit for an Examination', 'juken', 'じゅけん', '受験'),
      m('Lesson', 'jugyou', 'じゅぎょう', '授業'),
      m('Homework', 'shukudai', 'しゅくだい', '宿題'),
      m('Question', 'shitsumon', 'しつもん', '質問'),
      m('Exercises', 'renshuu mondai', 'れんしゅうもんだい', '練習問題'),
      m('Textbook', 'kyouka sho', 'きょうかしょ', '教科書'),
      m('Reference Book', 'sankou sho', 'さんこうしょ', '参考書'),
      m('Calculator', 'keisan ki', 'けいさんき', '計算器'),
      m('Bookshelf', 'hondana', 'ほんだな', '本棚'),
    ]),

    createSet('Bank words', 'bank', [
      m('Bank', 'ginkou', 'ぎんこう', '銀行'),
      m('Bank Staff', 'ginkouin', 'ぎんこういん', '銀行員'),
      m('Information Desk', 'uketsuke', 'うけつけ', '受付'),
      m('Teller Window', 'madoguchi', 'まどぐち', '窓口'),
      m('Numbered Ticket', 'bangou fuda', 'ばんごうふだ', '番号札'),
      m('Safe', 'kinko', 'きんこ', '金庫'),
      m('Safe-Deposit Box', 'kashi kinko', 'かしきんこ', '貸金庫'),
      m('Personal Seal', 'hanko', 'はんこ', '判子'),
      m('Personal Seal', 'inkan', 'いんかん', '印鑑'),
      m('Municipal Office / City Hall / Town Hall', 'shiyakusho', 'しやくしょ', '市役所'),
      m('National Health Insurance Card', 'kokumin kenkou hokenshou', 'こくみんけんこうほけんしょう', '国民健康保険証'),
      m('Bank Account', 'kouza', 'こうざ', '口座'),
      m('Basic Bank Account', 'futsuu kouza', 'ふつうこうざ', '普通口座'),
      m('Bank Account Number', 'kouza bangou', 'こうざばんごう', '口座番号'),
      m('Cash Card / ATM Card', 'kyasshu ka-do', 'キャッシュカード', 'キャッシュカード'),
      m('IC Card', 'aishii ka-do', 'IC カード', 'IC カード'),
      m('Cash Dispenser / Automatic Teller Machine', 'kyasshu disupensa-', 'キャッシュディスペンサー', 'キャッシュディスペンサー'),
      m('ATM', 'e-ti-emu', 'エーティーエム', 'エーティーエム'),
      m('PIN / Password Number', 'anshou bangou', 'あんしょうばんごう', '暗証番号'),
      m('Cash', 'genkin', 'げんきん', '現金'),
      m('Deposit', 'yokin', 'よきん', '預金'),
      m('Remittance', 'soukin', 'そうきん', '送金'),
      m('Loan', 'kashikin', 'かしきん', '貸金'),
      m('Loan', 'ro-n', 'ローン', 'ローン'),
      m('Debt', 'shakkin', 'しゃっきん', '借金'),
      m('Repayment', 'hensai', 'へんさい', '返済'),
      m('Cash Withdrawal', 'hikidashi', 'ひきだし', '引き出し'),
      m('Cash Deposit', 'azukeire', 'あずけいれ', '預け入れ'),
      m('Payment made via Bank Deposit Transfer', 'furikomi', 'ふりこみ', '振込'),
      m('Transfer money from one account to another / Giro', 'furikae', 'ふりかえ', '振替'),
      m('Balance', 'zandaka', 'ざんだか', '残高'),
      m('Balance Inquiry', 'zandaka shoukai', 'ざんだかしょうかい', '残高照会'),
      m('Entry / Registration', 'kichou', 'きちょう', '記帳'),
      m('Passbook / Bankbook', 'tsuuchou', 'つうちょう', '通帳'),
      m('Passbook Update', 'tsuuchou koushin', 'つうちょうこうしん', '通帳更新'),
      m('Paper Money / Bill / Note', 'shihei', 'しへい', '紙幣'),
      m('Coin / Hard Money', 'kouka', 'こうか', '硬貨'),
      m('Money Exchange', 'ryougae', 'りょうがえ', '両替'),
      m('Foreign Money Exchange', 'gaika ryougae', 'がいかりょうがえ', '外貨両替'),
      m('Service Charge / Commission', 'tesuuryou', 'てすうりょう', '手数料'),
      m('Bank Transfer Fee', 'furikomi tesuuryou', 'ふりこみてすうりょう', '振込手数料'),
      m('Payment Form', 'furikomi youshi', 'ふりこみようし', '振込用紙'),
      m('Dollar', 'doru', 'ドル', 'ドル'),
      m('Euro', 'yu-ro', 'ユーロ', 'ユーロ'),
    ]),

    createSet('IT words', 'it_words', [
      coto1('puroguramu', '–', 'プログラム', '(Computer) Program'),
      coto1('apuri', '–', 'アプリ', 'App'),
      coto1('burauza', '–', 'ブラウザ', 'Browser'),
      coto1('konpyuuta', '–', 'コンピュータ', 'Computer'),
      coto1('henkan', '変換', 'へんかん', 'Convert'),
      coto1('deita', '–', 'データ', 'Data'),
      coto1('desukutoppu', '–', 'デスクトップ', 'Desktop'),
      coto1('debaisu', '機器/デバイス', 'きき/デバイス', 'Device'),
      coto1('meiru', '–', 'メール', 'Email'),
      coto1('kakuchoushi', '拡張子', 'かくちょうし', 'File extension'),
      coto1('kansuu', '関数', 'かんすう', 'Function'),
      coto1('haadodoraibu', '–', 'ハードドライブ', 'Hard Drive'),
      coto1('haadouea', '–', 'ハードウエア', 'Hardware'),
      coto1('nyuuryoku', '入力', 'にゅうりょく', 'Input, to fill in'),
      coto1('intaanetto', '–', 'インターネット', 'Internet'),
      coto1('aipiadoresu', '–', 'IPアドレス', 'IP Address'),
      coto1('kiiboudo', '–', 'キーボード', 'Keyboard'),
      coto1('rapputoppu', '–', 'ラップトップ', 'Laptop'),
      coto1('kaisetsusho', '解説書', 'かいせつしょ', 'Manual'),
      coto1('monitaa', '–', 'モニター', 'Monitor'),
      coto1('mausu', '–', 'マウス', 'Mouse'),
      coto1('shutsuryoku', '出力', 'しゅつりょく', 'Output'),
      coto1('purintaa', '–', 'プリンター', 'Printer'),
      coto1('saikidou', '再起動', 'さいきどう', 'Restart'),
      coto1('uwagaki hozon', '(上書き) 保存', '(うわがき) ほぞん', 'Save'),
      coto1('gamen', '画面', 'がめん', 'Screen'),
      coto1('saabaa', '–', 'サーバー', 'Server'),
      coto1('settei', '設定', 'せってい', 'Settings'),
      coto1('supeisu/kuuhaku', 'スペース/空白', 'スペース/くうはく', 'Space'),
      coto1('kidou', '起動', 'きどう', 'Startup'),
      coto1('gijutsu', '技術', 'ぎじゅつ', 'Technology'),
      coto1('tanmatsu', '端末', 'たんまつ', 'Terminal'),
      coto1('tenpu', '添付', 'てんぷ', 'To attach'),
      coto1('asshuku', '圧縮', 'あっしゅく', 'To compress'),
      coto1('setsuzoku', '接続', 'せつぞく', 'To connect'),
      coto1('kopipe', '–', 'コピペ', 'To copy and paste'),
      coto1('kiritoru', '切り取る', 'きりとる', 'To cut'),
      coto1('kakidasu', '書き出す', 'かきだす', 'To export'),
      coto1('sounyuu', '挿入', 'そうにゅう', 'To insert'),
      coto1('haritsukeru', '貼り付ける', 'はりつける', 'To paste'),
      coto1('insatsu', '印刷', 'いんさつ', 'To print out'),
      coto1('kyouyuu', '共有', 'きょうゆう', 'To share'),
      coto1('kidou', '起動', 'きどう', 'To startup'),
      coto1('douki', '同期', 'どうき', 'To synchronize'),
      coto1('tacchipaddo', '–', 'タッチパッド', 'Touchpad'),
      coto1('uebusaito', '–', 'ウェブサイト', 'Website'),
    ]),
    createSet('Programming', 'programming', [
      coto1('tsuika', '追加', 'ついか', 'Add'),
      coto1('hikisuu', '引数', 'ひきすう', 'Argument, parameter'),
      coto1('hairetsu', '配列', 'はいれつ', 'Array'),
      coto1('jinkouchinou', '人工知能', 'じんこうちのう', 'Artificial intelligence, AI'),
      coto1('hidouki', '非同期', 'ひどうき', 'Asynchronous'),
      coto1('bakkendo', '–', 'バックエンド', 'Backend'),
      coto1('beitaban', 'ベータ版', 'ベータばん', 'Beta version'),
      coto1('bainari', '–', 'バイナリー', 'Binary'),
      coto1('nishinsuu', '二進数', 'にしんすう', 'Binary number'),
      coto1('bitto', '–', 'ビット', 'Bit'),
      coto1('buuru', '–', 'ブール', 'Boolean'),
      coto1('shingichi/shinrichi', '真偽値/真理値', 'しんぎち/しんりち', 'Boolean value'),
      coto1('bagu', '–', 'バグ', 'Bug'),
      coto1('birudo', '–', 'ビルド', 'Build (noun)'),
      coto1('kouru', '–', 'コール', 'Call'),
      coto1('moji', '文字', 'もじ', 'Character'),
      coto1('kurasu', '–', 'クラス', 'Class'),
      coto1('koudorebyuu', '–', 'コードレビュー', 'Code Review'),
      coto1('komandorain', '–', 'コマンドライン', 'Command Line'),
      coto1('konpairusuru', '–', 'コンパイルする', 'Compile'),
      coto1('sakusei', '作成', 'さくせい', 'Compose/create'),
      coto1('joukentsuki', '条件つき', 'じょうけんつき', 'Conditional'),
      coto1('teisuu', '定数', 'ていすう', 'Constant'),
      coto1('deitakouzou', 'データ構造', 'データこうぞう', 'Data Structure'),
      coto1('deitashurui', 'データ種類', 'データしゅるい', 'Data Type'),
      coto1('deitabeisu', '–', 'データベース', 'Database'),
      coto1('debaggu', '–', 'デバッグ', 'Debug'),
      coto1('debaggusuru', '–', 'デバッグする', 'Debugging'),
      coto1('sengen', '宣言', 'せんげん', 'Declaration'),
      coto1('fukugou', '復号', 'ふくごう', 'Decryption'),
      coto1('teigi', '定義', 'ていぎ', 'Define'),
      coto1('nouhin', '納品', 'のうひん', 'Delivery'),
      coto1('haibi', '配備', 'はいび', 'Deploy'),
      coto1('sekkei', '設計', 'せっけい', 'Design/architecture'),
      coto1('kaihatsusha', '開発者', 'かいはつしゃ', 'Developer'),
      coto1('kaihatsu', '開発', 'かいはつ', 'Development'),
      coto1('kaihatsukankyou', '開発環境', 'かいはつかんきょう', 'Development environment'),
      coto1('douteki', '動的', 'どうてき', 'Dynamic'),
      coto1('angouka', '暗号化', 'あんごうか', 'Encryption'),
      coto1('eraa', '–', 'エラー', 'Error'),
      coto1('ibento', '–', 'イベント', 'Event'),
      coto1('ibentohandoraa', '–', 'イベントハンドラー', 'Event Handler'),
      coto1('reigai', '例外', 'れいがい', 'Exception'),
      coto1('fureimuwaaku', '–', 'フレームワーク', 'Framework'),
      coto1('furontoendo', '–', 'フロントエンド', 'Front End'),
      coto1('furusutakku', '–', 'フルスタック', 'Full Stack'),
      coto1('kinou', '機能', 'きのう', 'Function'),
      coto1('kansuu', '関数 ', 'かんすう', 'Function'),
      coto1('HTTP rikuesuto', '–', 'HTTPリクエスト', 'HTTP Request'),
      coto1('jissou', '実装', 'じっそう', 'Implementation'),
      coto1('nyuuryoku', '入力', 'にゅうりょく', 'Input'),
      coto1('seisuu (gata)', '整数 (型)', 'せいすう (がた)', 'Integer (type)'),
      coto1('ruupu', '–', 'ループ', 'Loop'),
      coto1('kikaigakushuu', '機械学習', 'きかいがくしゅう', 'Machine Learning'),
      coto1('hoshu', '保守', 'ほしゅ', 'Maintenance'),
      coto1('kanri', '管理', 'かんり', 'Manage'),
      coto1('nyuurarunettowaaku', '–', 'ニューラルネットワーク', 'Neural Network'),
      coto1('nuru', '–', 'ヌル', 'Null'),
      coto1('obujekuto', '–', 'オブジェクト', 'Object'),
      coto1('obujekutoshikou', 'オブジェクト指向', 'オブジェクトしこう', 'Object-oriented'),
      coto1('unyou', '運用', 'うんよう', 'Operation'),
      coto1('enzanshi', '演算子', 'えんざんし', 'Operator'),
      coto1('autoputto', '–', 'アウトプット', 'Output'),
      coto1('heiretsushori', '並列処理', 'へいれつしょり', 'Parallel processing'),
      coto1('parameita', '–', 'パラメータ', 'Parameter'),
      coto1('pursesu/shori', 'プロセス/処理', 'プロセス/しょり', 'Process'),
      coto1('puroguramingu', '–', 'プログラミング', 'Programming'),
      coto1('konpyuutaagengo', 'コンピューター言語', 'コンピューターげんご', 'Programming language'),
      coto1('gijiransuu', '擬似乱数', 'ぎじらんすう', 'Pseudo-random number'),
      coto1('ransuu', '乱数', 'らんすう', 'Random number'),
      coto1('shouchousei', '冗長性', 'じょうちょうせい', 'Redundancy'),
      coto1('jikkou', '実行 ', 'じっこう', 'Run/execute'),
      coto1('sekyuritii', '–', 'セキュリティー', 'Security'),
      coto1('sofutouea', '–', 'ソフトウェア', 'Software'),
      coto1('sousu', '–', 'ソース', 'Source'),
      coto1('shou', '仕様', 'しよう', 'Specification'),
      coto1('supurinto', '–', 'スプリント', 'Sprint'),
      coto1('suteitomento', '–', 'ステートメント', 'Statement'),
      coto1('seiteki', '静的', 'せいてき', 'Static'),
      coto1('teishi', '停止', 'ていし', 'Stop'),
      coto1('kijiretsu', '文字列', 'もじれつ', 'String'),
      coto1('kouzou', '構造', 'こうぞう', 'Structure'),
      coto1('tagu', '–', 'タグ', 'Tag'),
      coto1('tesuto', '–', 'テスト', 'Test'),
      coto1('ninshou', '認証', 'にんしょう', 'To authenticate'),
      coto1('kaihatsu', '開発', 'かいはつ', 'To develop'),
      coto1('shori', '処理', 'しょり', 'To process (information)'),
      coto1('toukun', '–', 'トークン', 'Token'),
      coto1('taikenban', '体験版', 'たいけんばん', 'Trial version'),
      coto1('atai', '値', 'あたい', 'Value'),
      coto1('hensuu', '変数', 'へんすう', 'Variable'),
      coto1('kasou', '仮想', 'かそう', 'Virtual'),
      coto1('zeijakusei', '脆弱性', 'ぜいじゃくせい', 'Vulnerability'),
    ]),
    createSet('Body Parts', 'body', [
      m('organ (of body, plant, etc.)','kikan','きかん','器官'),
      m('brain','nou','のう','脳'),
      m('heart','shinzou','しんぞう','心臓'),
      m('liver','kanzou','かんぞう','肝臓'),
      m('kidney','jinzou','じんぞう','腎臓'),
      m('lung','hai','はい','肺'),
      m('stomach','i','い','胃'),
      m('guts; bowels; intestines','chou','ちょう','腸'),
      m('large intestine; large bowel; colon','daichou','だいちょう','大腸'),
      m('small intestine','shouchou','しょうちょう','小腸'),
      m('appendix','mouchou','もうちょう','盲腸'),
      m('rectum','chokuchou','ちょくちょう','直腸'),
      m('pancreas','suizou','すいぞう','膵臓'),
      m('spleen','hizou','ひぞう','脾臓'),
      m('gall bladder','tannou','たんのう','胆嚢'),
      m('lymph node','rinpasetsu','りんぱせつ','淋巴節'),
      m('urinary bladder','boukou','ぼうこう','膀胱'),
      m('skin','hifu','ひふ','皮膚'),
      m('blood','ketsueki','けつえき','血液'),
      m('blood','chi','ち','血'),
      m('blood vessel; vein','kekkan','けっかん','血管'),
      m('vein','jyoumyaku','じょうみゃく','静脈'),
      m('artery','doumyaku','どうみゃく','動脈'),
      m('muscle','kinniku','きんにく','筋肉'),
      m('bone','hone','ほね','骨'),
      m('bone marrow; medulla','kotsusui','こつずい','骨髄'),
      m('skeleton; skeletal structure; build; frame; physique','kokkaku','こっかく','骨格'),
      m('spine; backbone; spinal column','sehone','せぼね','背骨'),
      m('head','atama','あたま','頭'),
      m('forehead; brow','hitai','ひたい','額'),
      m('hair (on the head)','kaminoke','かみのけ','髪の毛'),
      m('neck','kubi','くび','首'),
      m('face','kao','かお','顔'),
      m('eye; eyes','me','め','目'),
      m('eye; pupil of the eye','hitomi','ひとみ','瞳'),
      m('eyebrow; eyebrows','mayu','まゆ','眉'),
      m('eyelashes','matsuge','まつげ','睫毛'),
      m('cheek','hoo','ほお','頬'),
      m('mouth','kuchi','くち','口'),
      m('lips','kuchibiru','くちびる','唇'),
      m('tongue','shita','した','舌'),
      m('tooth; teeth','ha','は','歯'),
      m('ear','mimi','みみ','耳'),
      m('nose','hana','はな','鼻'),
      m('arm','ude','うで','腕'),
      m('chin, jaw','ago','あご','顎'),
      m('moustache; beard','hige','ひげ','髭'),
      m('throat','nodo','のど','喉'),
      m('shoulder','kata','かた','肩'),
      m('hand','te','て','手'),
      m('elbow','hiji','ひじ','肘'),
      m('wrist','tekubi','てくび','手首'),
      m('finger','yubi','ゆび','指'),
      m('Index finger','hitosashiyubi','ひとさしゆび','人差し指'),
      m('Thumb','oyayubi','おやゆび','親指'),
      m('Middle finger; long finger; second finger; tall finger; middle toe; third toe','nakayubi','なかゆび','中指'),
      m('Ring finger; fourth finger','kusuriyubi','くすりゆび','薬指'),
      m('Little finger; pinky OR Little toe','koyubi','こゆび','小指'),
      m('nail (as in fingernail and toenail)','tsume','つめ','爪'),
      m('chest; breast','mune','むね','胸'),
      m('mind; heart; spirit','kokoro','こころ','心'),
      m('breast; nipple','chibusa','ちぶさ','乳房'),
      m('nipple; teat','chikubi','ちくび','乳首'),
      m('stomach','onaka','おなか','お腹'),
      m('abdomen; belly; stomach','hara','はら','腹'),
      m('naval; belly button','heso','へそ','臍'),
      m('back; spine','se','せ','背'),
      m('back of the body','senaka','せなか','背中'),
      m('back; lower back; waist; hips','koshi','こし','腰'),
      m('hips','youkan','ようかん','腰間'),
      m('hips; buttocks; backside','hippu','ヒップ','ヒップ'),
      m('buttocks; bottom','shiri','しり','尻'),
      m('thigh','momo','もも','股'),
      m('knee','hiza','ひざ','膝'),
      m('foot; leg','ashi','あし','足'),
      m('ankle','ashikubi','あしくび','足首'),
      m('heel','kakato','かかと','踵'),
      m('heel','heeru','ヒール','ヒール'),
      m('toes; tips of the toes','tsumasaki','つまさき','つま先'),
    ]),
    createSet('Professions', 'professions', [
      m('Accountant', 'kaikei shi', 'かいけいし', '会計士'),
      m('Actor / Actress / Performer', 'yakusha', 'やくしゃ', '役者'),
      m('Actor / Performer', 'haiyuu', 'はいゆう', '俳優'),
      m('Actress', 'joyuu', 'じょゆう', '女優'),
      m('Architect', 'kenchiku ka', 'けんちくか', '建築家'),
      m('Artist', 'geijutsu ka', 'げいじゅつか', '芸術家'),
      m('Author / Writer', 'sakka', 'さっか', '作家'),
      m('Bank Employee', 'ginkou in', 'ぎんこういん', '銀行員'),
      m('Barber', 'rihatsu shi', 'りはつし', '理髪師'),
      m('Barber', 'sanpatsuya', 'さんぱつや', '散髪屋'),
      m('Barber', 'tokoya', 'とこや', '床屋'),
      m('Baseball Player', 'yakyuu senshu', 'やきゅうせんしゅ', '野球選手'),
      m('Carpenter', 'daiku', 'だいく', '大工'),
      m('Chef', 'shefu', 'シェフ', 'シェフ'),
      m('Civil Servant / Government Worker', 'koumu in', 'こうむいん', '公務員'),
      m('Coach (Sports)', 'kantoku', 'かんとく', '監督'),
      m('Company Employee', 'kaisha in', 'かいしゃいん', '会社員'),
      m('Cook', 'kokku', 'コック', 'コック'),
      m('Cook / Chef', 'chouri shi', 'ちょうりし', '調理師'),
      m('Cook / Chef', 'ryouri nin', 'りょうりにん', '料理人'),
      m('Death from Overwork', 'karoushi', 'かろうし', '過労死'),
      m('Dentist', 'shikai', 'しかい', '歯科医'),
      m('Detective', 'tantei', 'たんてい', '探偵'),
      m('Doctor', 'isha', 'いしゃ', '医者'),
      m('Driver / Chauffeur', 'unten shu', 'うんてんしゅ', '運転手'),
      m('Engineer / Technologist', 'gi shi', 'ぎし', '技師'),
      m('Farmer', 'noumin', 'のうみん', '農民'),
      m('Female Nurse', 'kango fu', 'かんごふ', '看護婦'),
      m('Firefighter / Fireman', 'shoubou shi', 'しょうぼうし', '消防士'),
      m('Fisherman', 'ryou shi', 'りょうし', '漁師'),
      m('Fortuneteller / Diviner', 'uranai shi', 'うらないし', '占い師'),
      m('Hairdresser / Beauty Artist', 'biyou shi', 'びようし', '美容師'),
      m('Head Chef / Master Chef', 'ryouri chou', 'りょうりちょう', '料理長'),
      m('Hunter', 'ryou shi', 'りょうし', '猟師'),
      m('Journalist', 'ja-narisuto', 'ジャーナリスト', 'ジャーナリスト'),
      m('Judge', 'saiban kan', 'さいばんかん', '裁判官'),
      m('Lawyer / Attorney', 'bengo shi', 'べんごし', '弁護士'),
      m('Lecturer', 'kou shi', 'こうし', '講師'),
      m('Movie Director', 'kantoku', 'かんとく', '監督'),
      m('Nurse', 'kango shi', 'かんごし', '看護師'),
      m('Occupation', 'shoku gyou', 'しょくぎょう', '職業'),
      m('Painter / Artist', 'gaka', 'がか', '画家'),
      m('Part-time Worker', 'furi-ta-', 'フリーター', 'フリーター'),
      m('Pastor / Clergyman', 'boku shi', 'ぼくし', '牧師'),
      m('Performing Musician', 'ensou ka', 'えんそうか', '演奏家'),
      m('Photographer', 'shashin ka', 'しゃしんか', '写真家'),
      m('Pilot / Plane Captain', 'kichou', 'きちょう', '機長'),
      m('Policeman', 'kei kan', 'けいかん', '警官'),
      m('Policeman', 'keisatsu kan', 'けいさつかん', '警察官'),
      m('Policeman (Friendly term)', 'omawari san', 'おまわりさん', 'お巡りさん'),
      m('Politician', 'seiji ka', 'せいじか', '政治家'),
      m('Producer / Director', 'enshutsu ka', 'えんしゅつか', '演出家'),
      m('Professor', 'kyouju', 'きょうじゅ', '教授'),
      m('Real Estate Agent', 'fudousan gyousha', 'ふどうさんぎょうしゃ', '不動産業者'),
      m('Reporter', 'kisha', 'きしゃ', '記者'),
      m('Researcher', 'kenkyuu in', 'けんきゅういん', '研究員'),
      m('Scientist', 'kagaku sha', 'かがくしゃ', '科学者'),
      m('Secretary', 'hisho', 'ひしょ', '秘書'),
      m('Security Guard', 'keibi in', 'けいびいん', '警備員'),
      m('Shop Assistant', 'ten in', 'てんいん', '店員'),
      m('Singer', 'kashu', 'かしゅ', '歌手'),
      m('Soccer Player', 'sakka- senshu', 'サッカーせんしゅ', 'サッカー選手'),
      m('Soldier', 'hei shi', 'へいし', '兵士'),
      m('Speaker / Orator', 'enzetsu ka', 'えんぜつか', '演説家'),
      m('Station Worker / Station Attendant', 'eki in', 'えきいん', '駅員'),
      m('Stewardess / Female Flight Attendant', 'suchuwa-desu', 'スチュワーデス', 'スチュワーデス'),
      m('Supervisor / Superintendent', 'kantoku', 'かんとく', '監督'),
      m('Teacher', 'kyoushi', 'きょうし', '教師'),
      m('Teacher', 'sensei', 'せんせい', '先生'),
      m('Temporary Worker', 'hakensha in', 'はけんしゃいん', '派遣社員'),
      m('Tour Conductor / Tour Guide', 'tenjouin', 'てんじょういん', '添乗員'),
      m('Unemployed Person', 'mushoku sha', 'むしょくしゃ', '無職者'),
    ]),
    
    createSet('Office nouns', 'office_nouns', [
      m('Adhesive / Glue', 'secchakuzai', 'せっちゃくざい', '接着剤'),
      m('Ball-Point Pen', 'bo-rupen', 'ボールペン', 'ボールペン'),
      m('Binder', 'bainda-', 'バインダー', 'バインダー'),
      m('Blackboard', 'kokuban', 'こくばん', '黒板'),
      m('Book', 'hon', 'ほん', '本'),
      m('Box Cutter', 'katta-naifu', 'カッターナイフ', 'カッターナイフ'),
      m('Box for Holding Papers or Stationery', 'tebunko', 'てぶんこ', '手文庫'),
      m('Cardboard', 'danbo-ru', 'ダンボール', '段ボール'),
      m('Chalk', 'cho-ku', 'チョーク', 'チョーク'),
      m('Color Pencil', 'iroenpitsu', 'いろえんぴつ', '色鉛筆'),
      m('Colored Paper', 'irogami', 'いろがみ', '色紙'),
      m('Compass', 'konpasu', 'コンパス', 'コンパス'),
      m('Copier Paper / Photocopying Paper', 'kopi-youshi', 'コピーようし', 'コピー用紙'),
      m('Correction Fluid / Liquid Paper', 'shuuseieki', 'しゅうせいえき', '修正液'),
      m('Crayon', 'kureyon', 'クレヨン', 'クレヨン'),
      m('Desk', 'tsukue', 'つくえ', '机'),
      m('Diary / Journal', 'nikki', 'にっき', '日記'),
      m('Drawing Paper', 'gayoushi', 'がようし', '画用紙'),
      m('Drawing Pin / Thumb Tack', 'gabyou', 'がびょう', '画鋲'),
      m('Easel', 'gaka', 'がか', '画架'),
      m('Electronic Calculator', 'dentaku', 'でんたく', '電卓'),
      m('Envelope', 'fuutou', 'ふうとう', '封筒'),
      m('Eraser', 'keshigomu', 'けしゴム', '消しゴム'),
      m('Fabric Tape', 'nunote-pu', 'ぬのテープ', '布テープ'),
      m('File', 'fairu', 'ファイル', 'ファイル'),
      m('Folder', 'foruda-', 'フォルダー', 'フォルダー'),
      m('Fountain Pen', 'mannenhitsu', 'まんねんひつ', '万年筆'),
      m('Globe', 'chikyuugi', 'ちきゅうぎ', '地球儀'),
      m('Hole Puncher', 'anaakeki', 'あなあけき', '穴あけ器'),
      m('Marker', 'ma-ka-', 'マーカー', 'マーカー'),
      m('Masking Tape', 'masukingute-pu', 'マスキングテープ', 'マスキングテープ'),
      m('Mechanical Pencil', 'sha-pupenshiru', 'シャープペンシル', 'シャープペンシル'),
      m('Memo Book / Memo Pad', 'memochou', 'めもちょう', 'メモ帳'),
      m('Notebook', 'no-to', 'ノート', 'ノート'),
      m('Notebook / Memo Pad', 'techou', 'てちょう', '手帳'),
      m('Office Supplies / Stationery', 'jimuyouhin', 'じむようひん', '事務用品'),
      m('Packing Tape', 'gamute-pu', 'ガムテープ', 'ガムテープ'),
      m('Paint / Coloring Materials', 'enogu', 'えのぐ', '絵の具'),
      m('Paintbrush', 'efude', 'えふで', '絵筆'),
      m('Palette', 'paretto', 'パレット', 'パレット'),
      m('Paper', 'kami', 'かみ', '紙'),
      m('Paper Clip', 'kurippu', 'クリップ', 'クリップ'),
      m('Paste / Glue', 'nori', 'のり', '糊'),
      m('Pen and Ink / Writing Materials', 'hitsuboku', 'ひつぼく', '筆墨'),
      m('Pen Case', 'penke-su', 'ペンケース', 'ペンケース'),
      m('Pencil', 'enpitsu', 'えんぴつ', '鉛筆'),
      m('Pencil Case / Pencil Box', 'fudebako', 'ふでばこ', '筆箱'),
      m('Pencil Sharper', 'enpitsukezuri', 'えんぴつけずり', '鉛筆削り'),
      m('Penknife', 'pennaifu', 'ペンナイフ', 'ペンナイフ'),
      m('Permanent Marker', 'yuseipen', 'ゆせいペン', '油性ペン'),
      m('Permanent Marker', 'yuseimaakaa', 'ゆせいマーカー', '油性マーカー'),
      m('Picture / Drawing / Painting', 'e', 'え', '絵'),
      m('Postage Stamp', 'kitte', 'きって', '切手'),
      m('protractor', 'bundoki', 'ぶんどき', '分度器'),
      m('Rubber Band', 'wagomu', 'わゴム', '輪ゴム'),
      m('Ruler', 'jougi', 'じょうぎ', '定規'),
      m('Scissors', 'hasami', 'はさみ', '鋏'),
      m('Scotch Tape / Adhesive Tape', 'serote-pu', 'セロテープ', 'セロテープ'),
      m('Spare Lead / Lead Refill', 'kaeshin', 'かえしん', '替え芯'),
      m('Stamp / Seal', 'inkan', 'いんかん', '印鑑'),
      m('Staple', 'hocchikisu no hari', 'ホッチキスの針', 'ホッチキスの針'),
      m('Staple', 'sute-puru', 'ステープル', 'ステープル'),
      m('Stapler', 'hocchikisu', 'ホッチキス', 'ホッチキス'),
      m('Stationery', 'bunbougu', 'ぶんぼうぐ', '文房具'),
      m('Stationery', 'bungu', 'ぶんぐ', '文具'),
      m('Stationery', 'sute-shonari-', 'ステーショナリー', 'ステーショナリー'),
      m('Stationery Shop / Stationery Store', 'bunbouguya', 'ぶんぼうぐや', '文房具屋'),
      m('Stationery Shop / Stationery Store', 'bunguten', 'ぶんぐてん', '文具店'),
      m('Tag / Slip / Label', 'fusen', 'ふせん', '付箋'),
      m('Vermillion Inkpad used for Signature Seals', 'shuniku', 'しゅにく', '朱肉'),
      m('Writing Brush', 'fude', 'ふで', '筆'),
      m('Writing Implement / Writing Tool', 'hikkiyougu', 'ひっきようぐ', '筆記用具'),
      m('Writing Material', 'hikkigu', 'ひっきぐ', '筆記具'),
      m('Writing Pad', 'yousen', 'ようせん', '用箋'),
      m('Writing Paper', 'binsen', 'びんせん', '便箋'),
    ]),

    createSet('Places', 'places', [
      m('Airport', 'kuukou', 'くうこう', '空港'),
      m('Airport', 'hikoujou', 'ひこうじょう', '飛行場'),
      m('Aquarium', 'suizoku kan', 'すいぞくかん', '水族館'),
      m('Art Museum', 'bijutsu kan', 'びじゅつかん', '美術館'),
      m('Bakery', 'pan ya', 'パンや', 'パン屋'),
      m('Bank', 'ginkou', 'ぎんこう', '銀行'),
      m('Banquet Hall', 'enkaijou', 'えんかいじょう', '宴会場'),
      m('Bar / Pub (Japanese-style)', 'izaka ya', 'いざかや', '居酒屋'),
      m('Barbershop / Barber', 'toko ya', 'とこや', '床屋'),
      m('Beauty Salon / Hair Salon', 'biyouin', 'びよういん', '美容院'),
      m('Bookstore / Bookshop', 'hon ya', 'ほんや', '本屋'),
      m('Botanical Garden', 'shoku butsu en', 'しょくぶつえん', '植物園'),
      m('Building', 'tatemono', 'たてもの', '建物'),
      m('Butcher', 'niku ya', 'にくや', '肉屋'),
      m('Church', 'kyoukai', 'きょうかい', '教会'),
      m('Dormitory / Boarding House', 'kishuku sha', 'きしゅくしゃ', '寄宿舎'),
      m('Embassy', 'taishi kan', 'たいしかん', '大使館'),
      m('Factory', 'koujou', 'こうじょう', '工場'),
      m('Fish Dealer / Fishmonger', 'sakana ya', 'さかなや', '魚屋'),
      m('Florist', 'hana ya', 'はなや', '花屋'),
      m('Garden / Yard (within the house)', 'niwa', 'にわ', '庭'),
      m('Graduate School', 'daigaku in', 'だいがくいん', '大学院'),
      m('Greengrocery / Fruit and Vegetable Store', 'yao ya', 'やおや', '八百屋'),
      m('Grocery Store', 'shoku ryou hinten', 'しょくりょうひんてん', '食料品店'),
      m('Gymnasium', 'taiiku kan', 'たいいくかん', '体育館'),
      m('Hospital', 'byouin', 'びょういん', '病院'),
      m('Hostel / Dormitory', 'ryou', 'りょう', '寮'),
      m('Hot Spring', 'onsen', 'おんせん', '温泉'),
      m('Kindergarten', 'youchien', 'ようちえん', '幼稚園'),
      m('Library', 'tosho kan', 'としょかん', '図書館'),
      m('Market Place / Bazaar', 'ichiba', 'いちば', '市場'),
      m('Meeting Place / Assembly Hall', 'kaijou', 'かいじょう', '会場'),
      m('Memorial Hall', 'kinen kan', 'きねんかん', '記念館'),
      m('Movie Theater / Cinema', 'eiga kan', 'えいがかん', '映画館'),
      m('Municipal Office / City Hall / Town Hall', 'shiyaku sho', 'しやくしょ', '市役所'),
      m('Museum', 'haku butsu kan', 'はくぶつかん', '博物館'),
      m('Neighborhood', 'kinjo', 'きんじょ', '近所'),
      m('Nursery School', 'hoikuen', 'ほいくえん', '保育園'),
      m('Open Air Bath', 'roten buro', 'ろてんぶろ', '露天風呂'),
      m('Park / Garden (Public)', 'kouen', 'こうえん', '公園'),
      m('Pawnshop', 'shichi ya', 'しちや', '質屋'),
      m('Pharmacy', 'kusuri ya', 'くすりや', '薬屋'),
      m('Place / Location', 'basho', 'ばしょ', '場所'),
      m('Police Box', 'kouban', 'こうばん', '交番'),
      m('Post Office', 'yuubin kyoku', 'ゆうびんきょく', '郵便局'),
      m('Primary School / Elementary School', 'shou gakkou', 'しょうがっこう', '小学校'),
      m('Public Bathhouse', 'furo ya', 'ふろや', '風呂屋'),
      m('School', 'gakkou', 'がっこう', '学校'),
      m('Secondary School / Junior High School', 'chuu gakkou', 'ちゅうがっこう', '中学校'),
      m('Senior High School', 'koukou', 'こうこう', '高校'),
      m('Shop', 'mise', 'みせ', '店'),
      m('Shrine', 'jinja', 'じんじゃ', '神社'),
      m('Stationery Shop', 'bunbou gu ya', 'ぶんぼうぐや', '文房具屋'),
      m('Temple', 'tera', 'てら', '寺'),
      m('Traditional Japanese-style Inn', 'ryokan', 'りょかん', '旅館'),
      m('University', 'daigaku', 'だいがく', '大学'),
      m('Zoo', 'doubutsu en', 'どうぶつえん', '動物園'),
    ]),

    createSet('Train Stuff', 'trains', [
      m('(Ticket) Valid for one month', 'ikkagetsu yuukou', 'いっかげつゆうこう', '1ヶ月有効'),
      m('(Train) service suspended', 'unkyuu', 'うんきゅう', '運休'),
      m('~ Line', '~ sen', '～せん', '～線'),
      m('2nd Class Car', 'nitou sha', 'にとうしゃ', '二等車'),
      m('Accident resulting in personal injury or death', 'jinshin jiko', 'じんしんじこ', '人身事故'),
      m('Aisle Seat', 'tsuro gawa no seki', 'つうろがわのせき', '通路側の席'),
      m('Arrival', 'touchaku', 'とうちゃく', '到着'),
      m('Arrival Time', 'touchaku jikan', 'とうちゃくじかん', '到着時間'),
      m('Automatic Ticket Machine', 'jidou kenbai ki', 'じどうけんばいき', '自動券売機'),
      m('Bound for ~ (place)', '~ iki', '～いき', '～行き'),
      m('Boxed Lunch bought at a station', 'ekiben', 'えきべん', '駅弁'),
      m('Bullet Train / Shinkansen', 'shin kan sen', 'しんかんせん', '新幹線'),
      m('Cancel', 'torikeshi', 'とりけし', '取り消し'),
      m('Change (Money) / Balance', 'otsuri', 'おつり', 'お釣り'),
      m('Coupon Ticket', 'kaisuu ken', 'かいすうけん', '回数券'),
      m('Deadheading (train)', 'kaisou', 'かいそう', '回送'),
      m('Departure', 'shuppatsu', 'しゅっぱつ', '出発'),
      m('Departure of a train', 'hassha', 'はっしゃ', '発車'),
      m('Departure Time', 'shuppatsu jikan', 'しゅっぱつじかん', '出発時間'),
      m('Departure Time', 'hassha jikoku', 'はっしゃじこく', '発車時刻'),
      m('Destination', 'ikisaki', 'いきさき', '行き先'),
      m('Direction', 'houmen', 'ほうめん', '方面'),
      m('Discount Fare', 'waribiki ryoukin', 'わりびきりょうきん', '割引料金'),
      m('Down-train (going away from Tokyo)', 'kudari ressha', 'くだりれっしゃ', '下り列車'),
      m('Excess Fare (for riding extra stops)', 'norikoshi ryoukin', 'のりこしりょうきん', '乗り越し料金'),
      m('Express / Train that stops at major stations', 'kyuukou', 'きゅうこう', '急行'),
      m('Fare / Fee / Charge', 'ryoukin', 'りょうきん', '料金'),
      m('Fare for Children', 'kodomo ryoukin', 'こどもりょうきん', '子供料金'),
      m('Fare for Round Trip', 'oufuku ryoukin', 'おうふくりょうきん', '往復料金'),
      m('First Train', 'shiden', 'しでん', '始電'),
      m('First Train', 'ichiban ressha', 'いちばんれっしゃ', '一番列車'),
      m('First Train / First Departure', 'shihatsu', 'しはつ', '始発'),
      m('First Train / First Departure', 'shohatsu', 'しょはつ', '初発'),
      m('For ~ (direction)', '~ houmen', '～ほうめん', '～方面'),
      m('Going via / Going by way of', 'keiyu', 'けいゆ', '経由'),
      m('Green Car / 1st Class Car', 'guri-n sha', 'グリーンしゃ', 'グリーン車'),
      m('Last Stop / Terminal', 'shuuten', 'しゅうてん', '終点'),
      m('Last Train', 'saishuu densha', 'さいしゅうでんしゃ', '最終電車'),
      m('Last Train', 'shuuden', 'しゅうでん', '終電'),
      m('Last Train / Last Departure', 'shuuhatsu', 'しゅうはつ', '終発'),
      m('Limited Express (Faster than Express)', 'tokkyuu', 'とっきゅう', '特急'),
      m('Limited Express Ticket', 'tokkyuu ken', 'とっきゅうけん', '特急券'),
      m('Local Express', 'junkyuu', 'じゅんきゅう', '準急'),
      m('Main Line', 'honsen', 'ほんせん', '本線'),
      m('Night Train', 'yakou ressha', 'やこうれっしゃ', '夜行列車'),
      m('No-smoking Car', 'kinen sha', 'きんえんしゃ', '禁煙車'),
      m('Number 4 Train Car', 'yon gou sha', 'よんごうしゃ', '4 号車'),
      m('Numbers of Railway Cars', 'sharyou', 'しゃりょう', '車両'),
      m('One Day Travel Pass', 'ichinichi jousha ken', 'いちにちじょうしゃけん', '一日乗車券'),
      m('One way (trip)', 'katamichi', 'かたみち', '片道'),
      m('One Way Ticket', 'katamichi jousha ken', 'かたみちじょうしゃけん', '片道乗車券'),
      m('Ordinary / Train that stops at every station', 'futsuu', 'ふつう', '普通'),
      m('Passenger Fare / Transport Cost', 'unchin', 'うんちん', '運賃'),
      m('Passenger Ticket', 'jousha ken', 'じょうしゃけん', '乗車券'),
      m('Place for boarding (railway platform)', 'noriba', 'のりば', '乗り場'),
      m('Priority Seat', 'yuusen seki', 'ゆうせんせき', '優先席'),
      m('Private Railway', 'shitetsu', 'してつ', '私鉄'),
      m('Railroad / Railway', 'tetsudou', 'てつどう', '鉄道'),
      m('Railway Track', 'senro', 'せんろ', '線路'),
      m('Rapid-Service Train (Not as fast as Express)', 'kaisoku', 'かいそく', '快速'),
      m('Reserved Seat', 'shitei seki', 'していせき', '指定席'),
      m('Reserved Seat Ticket', 'shitei ken', 'していけん', '指定券'),
      m('Riding Past (ones station)', 'norikoshi', 'のりこし', '乗り越し'),
      m('Round Trip', 'oufuku', 'おうふく', '往復'),
      m('Round Trip Ticket', 'oufuku jousha ken', 'おうふくじょうしゃけん', '往復乗車券'),
      m('Route Map', 'rosenzu', 'ろせんず', '路線図'),
      m('Rush Hour', 'rasshuawa-', 'ラッシュアワー', 'ラッシュアワー'),
      m('Season Ticket / Commuter Pass', 'teiki ken', 'ていきけん', '定期券'),
      m('Seat', 'zaseki', 'ざせき', '座席'),
      m('Seat Number', 'zaseki bangou', 'ざせきばんごう', '座席番号'),
      m('Smoking Car', 'kitsuen sha', 'きつえんしゃ', '喫煙車'),
      m('Standard Seat', 'futsuu zaseki', 'ふつうざせき', '普通座席'),
      m('Station Attendant / Station Employee', 'ekiin', 'えきいん', '駅員'),
      m('Station Master / Station Manager', 'ekichou', 'えきちょう', '駅長'),
      m('Stopover', 'tochuugesha', 'とちゅうげしゃ', '途中下車'),
      m('Stopping (of a train)', 'teisha', 'ていしゃ', '停車'),
      m('Temporary suspension public transport service', 'unten miawase', 'うんてんみあわせ', '運転見合わせ'),
      m('Ticket', 'kippu', 'きっぷ', '切符'),
      m('Ticket Gate / Ticket Barrier / Wicket', 'kaisatsu guchi', 'かいさつぐち', '改札口'),
      m('Ticket Vending Machine', 'kippu hanbaiki', 'きっぷはんばいき', '切符販売機'),
      m('Ticket Window', 'mado guchi', 'まどぐち', '窓口'),
      m('Ticket Window', 'kippu uriba', 'きっぷうりば', '切符売り場'),
      m('Time Required', 'shoyou jikan', 'しょようじかん', '所要時間'),
      m('Track Number 3', 'san ban sen', 'さんばんせん', '3 番線'),
      m('Train (with 2 and above Railway Cars)', 'ressha', 'れっしゃ', '列車'),
      m('Train Conductor', 'shashou', 'しゃしょう', '車掌'),
      m('Train Schedule / Timetable', 'jikoku hyou', 'じこくひょう', '時刻表'),
      m('Train that stops at every station', 'kakueki teisha', 'かくえきていしゃ', '各駅停車'),
      m('Transfer / Change (Train)', 'norikae', 'のりかえ', '乗り換え'),
      m('Underground Train / Subway', 'chikatetsu', 'ちかてつ', '地下鉄'),
      m('Unreserved Seat', 'jiyuu seki', 'じゆうせき', '自由席'),
      m('Up-train (going towards Tokyo)', 'nobori ressha', 'のぼりれっしゃ', '上り列車'),
      m('Window Seat', 'mado gawa no seki', 'まどがわのせき', '窓側の席'),
      m('Women-only Carriage on a train', 'josei senyou sharyou', 'じょせいせんようしゃりょう', '女性専用車両'),
    ]),

    createSet('Travel', 'travel', [
      m('2 Days 1 Night', 'ippaku futsuka', 'いっぱくふつか', '一泊二日'),
      m('3 Days 2 Nights', 'nihaku mikka', 'にはくみっか', '二泊三日'),
      m('4 Days 3 Nights', 'sanpaku yokka', 'さんぱくよっか', '三泊四日'),
      m('Airport', 'kuukou', 'くうこう', '空港'),
      m('Baggage / Luggage', 'nimotsu', 'にもつ', '荷物'),
      m('Capsule Hotel', 'kapuseru hoteru', 'カプセルホテル', 'カプセルホテル'),
      m('Check-in', 'chekku in', 'チェックイン', 'チェックイン'),
      m('Check-out', 'chekku auto', 'チェックアウト', 'チェックアウト'),
      m('Currency Exchange', 'ryougae', 'りょうがえ', '両替'),
      m('Currency Exchange Rate', 'kawase re-to', 'かわせレート', '為替レート'),
      m('Currency Exchange Shop', 'ryougae ya', 'りょうがえや', '両替屋'),
      m('Day Trip', 'higaeri ryokou', 'ひがえりりょこう', '日帰り旅行'),
      m('Destination', 'ryokou saki', 'りょこうさき', '旅行先'),
      m('Foreign Travel / Oversea Trip', 'gaikoku ryokou', 'がいこくりょこう', '外国旅行'),
      m('Front / Reception Desk', 'furonto', 'フロント', 'フロント'),
      m('Global Travel', 'sekai ryokou', 'せかいりょこう', '世界旅行'),
      m('Group Tour', 'dantai ryokou', 'だんたいりょこう', '団体旅行'),
      m('Guiding', 'annai', 'あんない', '案内'),
      m('Hand Baggage / Hand Luggage', 'te nimotsu', 'てにもつ', '手荷物'),
      m('Honeymoon', 'shinkon ryokou', 'しんこんりょこう', '新婚旅行'),
      m('Hostel', 'hosuteru', 'ホステル', 'ホステル'),
      m('Hotel', 'hoteru', 'ホテル', 'ホテル'),
      m('Information Bureau', 'annaijo', 'あんないじょ', '案内所'),
      m('Interpretation', 'tsuu yaku', 'つうやく', '通訳'),
      m('Interpreter', 'tsuu yaku sha', 'つうやくしゃ', '通訳者'),
      m('Japanese-style Inn', 'ryokan', 'りょかん', '旅館'),
      m('Lecture Tour', 'kouen ryokou', 'こうえんりょこう', '講演旅行'),
      m('Observation Tour', 'kengaku ryokou', 'けんがくりょこう', '見学旅行'),
      m('Overseas Travel / Traveling Abroad', 'kaigai ryokou', 'かいがいりょこう', '海外旅行'),
      m('Package Tour', 'pakku ryokou', 'パックりょこう', 'パック旅行'),
      m('Package Tour', 'pakku tsua-', 'パックツアー', 'パックツアー'),
      m('Paid Trip (All expenses)', 'shoutai ryokou', 'しょうたいりょこう', '招待旅行'),
      m('Pamphlet / Booklet', 'pan furetto', 'パンフレット', 'パンフレット'),
      m('Personal Tour', 'kojin ryokou', 'こじんりょこう', '個人旅行'),
      m('Reservation', 'yoyaku', 'よやく', '予約'),
      m('Resort', 'rizo-to', 'リゾート', 'リゾート'),
      m('School Excursion / School Trip', 'shuugaku ryokou', 'しゅうがくりょこう', '修学旅行'),
      m('Scientific Expedition', 'kenkyuu ryokou', 'けんきゅうりょこう', '研究旅行'),
      m('Season for Traveling', 'ryokou shi-zun', 'りょこうシーズン', '旅行シーズン'),
      m('Sight-seeing Area', 'kankou chi', 'かんこうち', '観光地'),
      m('Sightseeing Tour', 'kankou ryokou', 'かんこうりょこう', '観光旅行'),
      m('Single Bedroom', 'shinguru', 'シングル', 'シングル'),
      m('Souvenir / Gift', 'omiyage', 'おみやげ', 'お土産'),
      m('Tour', 'tsua-', 'ツアー', 'ツアー'),
      m('Tour Conductor', 'tenjou in', 'てんじょういん', '添乗員'),
      m('Tour Guide', 'gaido', 'ガイド', 'ガイド'),
      m('Tourist', 'kankou kyaku', 'かんこうきゃく', '観光客'),
      m('Tourist / Traveler', 'ryokou sha', 'りょこうしゃ', '旅行者'),
      m('Travel / Trip / Journey', 'tabi', 'たび', '旅'),
      m('Travel / Trip / Tour', 'ryokou', 'りょこう', '旅行'),
      m('Travel Agency', 'ryokou dairiten', 'りょこうだいりてん', '旅行代理店'),
      m('Travel Agent', 'ryokou gyousha', 'りょこうぎょうしゃ', '旅行業者'),
      m('Travel Company', 'ryokou gaisha', 'りょこうがいしゃ', '旅行会社'),
      m('Travel Expenses', 'ryokou hiyou', 'りょこうひよう', '旅行費用'),
      m('Travel Expenses', 'ryohi', 'りょひ', '旅費'),
      m('Travel Insurance', 'ryokou hoken', 'りょこうほけん', '旅行保険'),
      m('Travel Schedule / Travel Itinerary', 'ryokou nittei', 'りょこうにってい', '旅行日程'),
      m('Travelers Check', 'ryokou shayou kogitte', 'りょこうしゃようこぎって', '旅行者用小切手'),
      m('Twin Bedroom', 'tsuin', 'ツイン', 'ツイン'),
      m('Youth Hostel', 'yu-su hosuteru', 'ユースホステル', 'ユースホステル'),
    ]),

    createSet('Signage', 'signage', [
      m('(Lady) Powder Room / Lavatory', 'keshou shitsu', 'けしょうしつ', '化粧室'),
      m('(Machine) Out Of Order', 'koshou chuu', 'こしょうちゅう', '故障中'),
      m('(Shop) Not Yet Open / In Preparation', 'junbi chuu', 'じゅんびちゅう', '準備中'),
      m('(Shop) Open / In Business', 'eigyou chuu', 'えいぎょうちゅう', '営業中'),
      m('(Toilet) Occupied / In Use', 'shiyou chuu', 'しようちゅう', '使用中'),
      m('(Train) Priority Seat', 'yuusen seki', 'ゆうせんせき', '優先席'),
      m('Business Hours', 'eigyou jikan', 'えいぎょうじかん', '営業時間'),
      m('Car Park', 'chuusha jou', 'ちゅうしゃじょう', '駐車場'),
      m('Changing Room', 'koui shitsu', 'こういしつ', '更衣室'),
      m('Conference Room / Meeting Room', 'kaigi shitsu', 'かいぎしつ', '会議室'),
      m('Danger', 'kiken', 'きけん', '危険'),
      m('Emergency Exit', 'hijou guchi', 'ひじょうぐち', '非常口'),
      m('Exit and Entrance', 'deiri guchi', 'でいりぐち', '出入口'),
      m('Fire Hydrant', 'shou ka sen', 'しょうかせん', '消火栓'),
      m('Fireproof Door', 'bouka tobira', 'ぼうかとびら', '防火扉'),
      m('Free Delivery', 'muryou haitatsu', 'むりょうはいたつ', '無料配達'),
      m('Free Parking', 'muryou chuusha jou', 'むりょうちゅうしゃじょう', '無料駐車場'),
      m('Healthcare Room / School Infirmary', 'hoken shitsu', 'ほけんしつ', '保健室'),
      m('Home Delivery Service', 'taku haibin', 'たくはいびん', '宅配便'),
      m('Information Desk', 'annai jo', 'あんないじょ', '案内所'),
      m('Lecture Room', 'kougi shitsu', 'こうぎしつ', '講義室'),
      m('Mail Delivery / Postal Delivery', 'yuubin haitatsu', 'ゆうびんはいたつ', '郵便配達'),
      m('Mailbox', 'yuubin bako', 'ゆうびんばこ', '郵便箱'),
      m('Monthly-paid Car Park', 'tsuki gime chuusha jou', 'つきぎめちゅうしゃじょう', '月極駐車場'),
      m('No Entry / No Trepassing / Keep Out', 'tachiiri kinshi', 'たちいりきんし', '立入禁止'),
      m('No Flammable', 'kaki genkin', 'かきげんきん', '火気厳禁'),
      m('No Parking', 'chuusha kinshi', 'ちゅうしゃきんし', '駐車禁止'),
      m('No Smoking', 'kinen', 'きんえん', '禁煙'),
      m('No Smoking Seat', 'kinen seki', 'きんえんせき', '禁煙席'),
      m('Public Bathhouse', 'koushuu yokujou', 'こうしゅうよくじょう', '公衆浴場'),
      m('Public Telephone', 'koushuu denwa', 'こうしゅうでんわ', '公衆電話'),
      m('Public Toilet', 'koushuu toire', 'こうしゅうトイレ', '公衆トイレ'),
      m('Public Toilet / Public Restroom', 'koushuu benjo', 'こうしゅうべんじょ', '公衆便所'),
      m('Real Estate', 'fudou san', 'ふどうさん', '不動産'),
      m('Recruitment', 'boshuu', 'ぼしゅう', '募集'),
      m('Reserved Car Park', 'senyou chuusha jou', 'せんようちゅうしゃじょう', '専用駐車場'),
      m('Room Available', 'kuu shitsu ari', 'くうしつあり', '空室有り'),
      m('Sign', 'sain', 'サイン', 'サイン'),
      m('Signboard', 'kanban', 'かんばん', '看板'),
      m('Smoking', 'kitsuen', 'きつえん', '喫煙'),
      m('Smoking Area', 'kitsuen jo', 'きつえんじょ', '喫煙所'),
      m('Smoking Seat', 'kitsuen seki', 'きつえんせき', '喫煙席'),
      m('Toll Car Park', 'yuuryou chuusha jou', 'ゆうりょうちゅうしゃじょう', '有料駐車場'),
    ]),

    createSet('Vegetables', 'veggies', [
      m('Bamboo Shoot', 'takenoko', 'たけのこ', '竹の子 / 筍 / 笋'),
      m('Bean Sprouts', 'moyashi', 'もやし', '萌やし'),
      m('Beans / Peas', 'mame', 'まめ', '豆'),
      m('Bitter Melon', 'go-ya', 'ゴーヤ', 'ゴーヤ'),
      m('Bok Choy', 'chingensai', 'チンゲンサイ', '青梗菜'),
      m('Broad Bean', 'soramame', 'そらまめ', '空豆'),
      m('Broccoli', 'burokkori-', 'ブロッコリー', 'ブロッコリー'),
      m('Cabbage', 'kyabetsu', 'キャベツ', 'キャベツ'),
      m('Carrot', 'ninjin', 'にんじん', '人参'),
      m('Cashew Nut', 'kashu- nattsu', 'カシューナッツ', 'カシューナッツ'),
      m('Cauliflower', 'karifurawa-', 'カリフラワー', 'カリフラワー'),
      m('Celery', 'serori', 'セロリ', 'セロリ'),
      m('Chinese Chive', 'nira', 'にら', '韮'),
      m('Chinese Yam', 'nagaimo', 'ながいも', '長芋'),
      m('Cloud Ear Mushroom / Wood Ear Mushroom', 'kikurage', 'きくらげ', '木耳'),
      m('Corn / Maize', 'toumorokoshi', 'トウモロコシ', '玉蜀黍'),
      m('Cucumber', 'kyuuri', 'きゅうり', '胡瓜'),
      m('Edible Chrysanthemum', 'shungiku', 'しゅんぎく', '春菊'),
      m('Eggplant', 'nasu', 'ナス', '茄子'),
      m('Enoki Mushroom', 'enokitake', 'えのきたけ', '榎茸'),
      m('Garden Peas / Podded Peas', 'sayaendou', 'さやえんどう', '莢豌豆'),
      m('Garlic', 'ninniku', 'にんにく', '大蒜'),
      m('Ginger', 'shouga', 'しょうが', '生姜'),
      m('Great Burdock', 'gobou', 'ごぼう', '牛蒡'),
      m('Green Peas', 'endou', 'えんどう', '豌豆'),
      m('Green Pepper', 'pi-man', 'ピーマン', 'ピーマン'),
      m('Green Perilla', 'aojiso', 'あおジソ', '青紫蘇'),
      m('Green Soybeans', 'edamame', 'えだまめ', '枝豆'),
      m('Green Spring Onion', 'aonegi', 'あおねぎ', '青葱'),
      m('Hen-of-the-woods Mushroom', 'maitake', 'まいたけ', '舞茸'),
      m('Japanese Citrus Fruit / Japanese Lime', 'kabosu', 'カボス', '香母酢'),
      m('Japanese Ginger', 'myouga', 'みょうが', '茗荷'),
      m('Japanese Honewort / Japanese Parsley', 'mitsuba', 'みつば', '三つ葉'),
      m('Japanese Mustard / Spider Mustard', 'mizuna', 'ミズナ', '水菜'),
      m('Japanese Mustard Spinach', 'komatsuna', 'こまつな', '小松菜'),
      m('Japanese Pepper', 'sanshou', 'さんしょう', '山椒'),
      m('Japanese Yam', 'yamatoimo', 'やまといも', '大和芋'),
      m('Japanese Yam (general term)', 'yamaimo', 'ヤマイモ', '山芋'),
      m('Java Water Dropwort', 'seri', 'セリ', '芹'),
      m('King Trumpet Mushroom / King Oyster Mushroom', 'eringi', 'エリンギ', 'エリンギ'),
      m('Lettuce', 'retasu', 'レタス', 'レタス'),
      m('Lotus Root', 'renkon', 'レンコン', '蓮根'),
      m('Matsutake Mushroom', 'matsutake', 'まつたけ', '松茸'),
      m('Melon Cucumber', 'shirouri', 'しろうり', '白瓜'),
      m('Mushroom', 'kinoko', 'キノコ', '茸'),
      m('Nameko Mushroom', 'nameko', 'ナメコ', '滑子'),
      m('Napa Cabbage / Chinese Cabbage', 'hakusai', 'はくさい', '白菜'),
      m('Nut', 'nattsu', 'ナッツ', 'ナッツ'),
      m('Okra', 'okura', 'オクラ', 'オクラ'),
      m('Onion', 'tamanegi', 'たまねぎ', '玉葱'),
      m('Oyster Mushroom', 'hiratake', 'ひらたけ', '平茸'),
      m('Parsley', 'paseri', 'パセリ', 'パセリ'),
      m('Pea Sprouts', 'toumyou', 'トウミョウ', '豆苗'),
      m('Peanut', 'pi-nattsu', 'ピーナッツ', 'ピーナッツ'),
      m('Perilla Leaf', 'shiso', 'シソ', '紫蘇'),
      m('Pickled Dried Plum', 'umeboshi', 'うめぼし', '梅干'),
      m('Potato', 'jagaimo', 'ジャガイモ', 'ジャガイモ'),
      m('Pumpkin', 'kabocha', 'かぼちゃ', '南瓜'),
      m('Red Perilla', 'akajiso', 'あかジソ', '赤紫蘇'),
      m('Red Pickled Ginger', 'beni shouga', 'べにしょうが', '紅生姜'),
      m('Shiitake Mushroom', 'shiitake', 'しいたけ', '椎茸'),
      m('Shimeji Mushroom', 'shimeji', 'シメジ', '占地'),
      m('Shishito / Small Sweet Green Pepper', 'shishi tougarashi', 'ししとうがらし', '獅子唐辛子'),
      m('Soya bean', 'daizu', 'だいず', '大豆'),
      m('Spinach', 'hourensou', 'ほうれんそう', '菠薐草'),
      m('Strips of Dried Gourd', 'kanpyou', 'かんぴょう', '乾瓢 / 干瓢'),
      m('Sweet Potato', 'satsumaimo', 'サツマイモ', 'サツマイモ'),
      m('Taro / Dasheen / Eddo', 'satoimo', 'サトイモ', '里芋'),
      m('Turnip', 'kabu', 'かぶ', '蕪'),
      m('Turnip', 'suzuna', 'スズナ', '菘 / 鈴菜'),
      m('Vegetable', 'yasai', 'やさい', '野菜'),
      m('Wasabi', 'wasabi', 'わさび', '山葵'),
      m('Welsh Onion / Green Onion', 'negi', 'ねぎ', '葱'),
      m('White Radish', 'daikon', 'だいこん', '大根'),
      m('White Radish Sprouts', 'kaiwarena', 'かいわれな', '貝割れ菜'),
      m('White Spring Onion', 'shironegi', 'しろねぎ', '白葱'),

    ]),

    createSet('Animals', 'animals', [
      m('zebra','shimauma','しまうま','縞馬'),
      m('zebra','zebura','ゼブラ','ゼブラ'),
      m('moose, elk','herajika','へらじか','箆鹿'),
      m('large deer, moose, elk','oojika','おおじか','大鹿'),
      m('moose','muusu','ムース','ムース'),
      m('lion','raion','ライオン','ライオン'),
      m('chimpanzee','chinpanji','チンパンジー','チンパンジー'),
      m('chimpanzee','kuroshoujyou','くろしょうじょう','黒猩々'),
      m('orangutan','shoujyou','しょうじょう','猩々'),
      m('gorilla','gorira','ゴリラ','ゴリラ'),
      m('tortoise','kame','かめ','亀'),
      m('kangaroo','kangaruu','カンガルー','カンガルー'),
      m('peacock','kujyaku','くじゃく','孔雀'),
      m('camel','rakuda','らくだ','駱駝'),
      m('sheep','hitsuji','ひつじ','羊'),
      m('goat','yagi','やぎ','山羊'),
      m('hippopotamus','kaba','かば','河馬'),
      m('giraffe','kirin','キリン','麒麟'),
      m('mouse; rat','nezumi','ねずみ','鼠'),
      m('monkey','saru','さる','猿'),
      m('elephant','zou','ぞう','象'),
      m('snake','hebi','へび','蛇'),
      m('tiger','tora','とら','虎'),
      m('deer','shika','しか','鹿'),
      m('pig','buta','ぶた','豚'),
      m('cow','ushi','うし','牛'),
      m('chicken','niwatori','にわとり','鶏'),
      m('horse','uma','うま','馬'),
      m('insect; bug; cricket; moth; worm','mushi','むし','虫'),
      m('insect; bug','konchuu','こんちゅう','昆虫'),
      m('ant','ari','あり','蟻'),
      m('termite; white ant','shiroari','しろあり','白蟻'),
      m('cockroach','gokiburi','ごきぶり','蜚蠊'),
      m('ladybug','tentou mushi','てんとうむし','てんとう虫'),
      m('bee; wasp; hornet','hachi','はち','蜂'),
      m('firefly','hotaru','ほたる','蛍'),
      m('rhinoceros beetle','kabutomushi','かぶとむし','甲虫'),
      m('dragonfly','tonbo','とんぼ','蜻蛉'),
      m('grasshopper','batta','ばった','飛蝗'),
      m('butterfly','chou','ちょう','蝶'),
      m('hornworm (caterpillar of a hawk moth); (hairless) caterpillar','imo mushi','いもむし','芋虫'),
      m('caterpillar, esp. hairless','hadaka mushi','はだかむし','裸虫'),
      m('hairy caterpillar','kemushi','けむし','毛虫'),
      m('aphid','aburamushi','あぶらむし','油虫'),
      m('cricket','koorogi','こおろぎ','蟋蟀'),
      m('cicada','semi','せみ','蝉'),
      m('spider','kumo','くも','蜘蛛'),
      m('mosquito','ka','か','蚊'),
      m('worm; insect','mushikera','むしけら','虫螻'),
      m('roundworm','kaichuu','かいちゅう','回虫'),
      m('earthworm','mimizu','みみず','蚯蚓'),
      m('centipede','mukade','むかで','百足'),
      m('millipede','yasude','やすで','馬陸'),
      m('fly','hae','はえ','蝿'),
      m('moth','ga','が','蛾'),
      m('fruit fly','shoijyoi hae','しょうじょうばえ','猩猩蠅'),
      m('maggot','ujimushi','うじむし','蛆虫'),
      m('water strider','amenbo','あめんぼ','水黽'),
      m('shark', 'same', 'さめ', '鮫'),
      m('shellfish','kairui','かいるい','貝類'),
      m('shell; shellfish','kai','かい','貝'),
      m('marine products; seafood; fish and shellfish','gyokairui','ぎょかいるい','魚介類'),
      m('Tuna','maguro','まぐろ','鮪'),
      m('young Japanese amberjack; young yellowtail','hamachi','はまち','魬'),
      m('mackerel','saba','さば','鯖'),
      m('sea bream','tai','たい','鯛'),
      m('stingray','ei','えい','海鷂魚'),
      m('jellyfish','kurage','くらげ','海月'),
      m('sea cucumber','namako','なまこ','海鼠'),
      m('walrus','kaiba','かいば','海馬'),
      m('seahorse; sea horse','tatsu no oto shigo','たつのおとしご','竜の落し子'),
      m('true seal','azarashi','あざらし','海豹'),
      m('sea lion','ashika','あしか','海驢'),
      m('whale','kujira','くじら','鯨'),
      m('dolphin, porpoises, belugas, etc.','iruka','いるか','海豚'),
      m('dolphin','dorufin','ドルフィン','ドルフィン'),
      m('salmon','sake','さけ','鮭'),
      m('trout; sea trout','masu','ます','鱒'),
      m('octopus','tako','たこ','蛸'),
      m('sea otter','rakko','らっこ','海獺'),
      m('eel (esp Japanese eel)','unagi','うなぎ','鰻'),
      m('catfish','namazu','なまず','鯰'),
      m('tai, species of red Pacific sea bream','madai','まだい','真鯛'),
      m('spiny lobster','ise\'ebi','いせえび','伊勢海老'),
      m('puffer fish','fugu','ふぐ','河豚'),
      m('swordfish','mekajiki','めかじき','眼梶木'),
      m('marlin; swordfish; spearfish; sailfish','kajiki','かじき','梶木'),
      m('sea urchin; sea urchin eggs','uni','うに','雲丹'),
      m('abalone','awabi','あわび','鮑'),
      m('cod; haddock','tara','たら','鱈'),
      m('oyster','kaki','かき','牡蠣'),
      m('penguin','pengin','ペンギン','ペンギン'),
      m('walrus','seiuchi','せいうち','海象'),
      m('polar bear','hokkyokuguma','ほっきょくぐま','北極熊'),
    ]),

    createSet('Nature and Weather', 'nature_weather', [
      m('Acid Rain', 'sanseiu', 'さんせいう', '酸性雨'),
      m('Air', 'kuuki', 'くうき', '空気'),
      m('Atmospheric Pressure', 'kiatsu', 'きあつ', '気圧'),
      m('Autumn / Fall', 'aki', 'あき', '秋'),
      m('Branch / Twig / Bough', 'eda', 'えだ', '枝'),
      m('Cave', 'doukutsu', 'どうくつ', '洞窟'),
      m('Clear Weather / Fair Weather', 'hare', 'はれ', '晴れ'),
      m('Cliff', 'gake', 'がけ', '崖'),
      m('Cloud', 'kumo', 'くも', '雲'),
      m('Cloud', 'kumo', 'くも', '雲'),
      m('Cloudy Weather', 'kumori', 'くもり', '曇り'),
      m('Downpour', 'gouu', 'ごうう', '豪雨'),
      m('Dry Season', 'kanki', 'かんき', '乾季'),
      m('Dryness', 'kansou', 'かんそう', '乾燥'),
      m('Earth / Soil', 'tsuchi', 'つち', '土'),
      m('Earthquake', 'jishin', 'じしん', '地震'),
      m('Earthquake', 'jishin', 'じしん', '地震'),
      m('Earthquake Center / Seismic Center', 'shingen', 'しんげん', '震源'),
      m('Field', 'hatake', 'はたけ', '畑'),
      m('Fine Weather / Clear and Sunny', 'kaisei', 'かいせい', '快晴'),
      m('Flood', 'kouzui', 'こうずい', '洪水'),
      m('Flower', 'hana', 'はな', '花'),
      m('Fog / Mist', 'kiri', 'きり', '霧'),
      m('Forest (Bigger than hayashi)', 'mori', 'もり', '森'),
      m('Fountain / Spring', 'izumi', 'いずみ', '泉'),
      m('Four Seasons', 'shiki', 'しき', '四季'),
      m('Grass', 'kusa', 'くさ', '草'),
      m('hail', 'hyou', 'ひょう', '雹'),
      m('hailstone / Falling Iceball', 'arare', 'あられ', '霰'),
      m('Heavy Fog / Dense Mist', 'noumu', 'のうむ', '濃霧'),
      m('Heavy Rain', 'ooame', 'おおあめ', '大雨'),
      m('Heavy Snow', 'ooyuki', 'おおゆき', '大雪'),
      m('High Atmospheric Pressure', 'kou kiatsu', 'こうきあつ', '高気圧'),
      m('Hill / Knoll', 'oka', 'おか', '丘'),
      m('Hot Spring', 'onsen', 'おんせん', '温泉'),
      m('Ice Day', 'ma fuyu bi', 'まふゆび', '真冬日'),
      m('Island', 'shima', 'しま', '島'),
      m('Japanese Earthquake Scale', 'shindo', 'しんど', '震度'),
      m('Lake', 'mizuumi', 'みずうみ', '湖'),
      m('Land Breeze', 'rikufuu', 'りくふう', '陸風'),
      m('Leaf', 'ha', 'は', '葉'),
      m('Level of Humidity', 'shitsu do', 'しつど', '湿度'),
      m('Light Rain / Drizzle', 'kosame', 'こさめ', '小雨'),
      m('Low Atmospheric Pressure', 'tei kiatsu', 'ていきあつ', '低気圧'),
      m('Maximum Temperature', 'saikou kion', 'さいこうきおん', '最高気温'),
      m('Minimum Temperature', 'saitei kion', 'さいていきおん', '最低気温'),
      m('Misty Rain / Light Drizzle', 'kiri same', 'きりさめ', '霧雨'),
      m('Moisture / Humidity / Damp', 'shikke', 'しっけ', '湿気'),
      m('Monsoon / Seasonal Wind', 'kisetsu fuu', 'きせつふう', '季節風'),
      m('Moon', 'tsuki', 'つき', '月'),
      m('Mountain', 'yama', 'やま', '山'),
      m('Nature', 'shizen', 'しぜん', '自然'),
      m('Ocean Waves', 'harou', 'はろう', '波浪'),
      m('Passing Shower', 'toori ame', 'とおりあめ', '通り雨'),
      m('Pond', 'ike', 'いけ', '池'),
      m('Rain', 'ame', 'あめ', '雨'),
      m('Rain', 'ame', 'あめ', '雨'),
      m('Rain Shower / Sudden Shower', 'niwaka ame', 'にわかあめ', '俄雨'),
      m('Rainbow', 'niji', 'にじ', '虹'),
      m('Rainstorm', 'boufuuu', 'ぼうふうう', '暴風雨'),
      m('Rainy Season', 'tsuyu / baiu', 'つゆ / ばいう', '梅雨'),
      m('Rainy Season', 'uki', 'うき', '雨季'),
      m('Regional Rain', 'kyoku chi teki na ame', 'きょくちてきなあめ', '局地的な雨'),
      m('River / Stream', 'kawa', 'かわ', '川/河'),
      m('Rock / Crag', 'iwa', 'いわ', '岩'),
      m('Sand', 'suna', 'すな', '砂'),
      m('Scenery / Landscape', 'keshiki', 'けしき', '景色'),
      m('Sea', 'umi', 'うみ', '海'),
      m('Sea Breeze', 'umikaze / kaifuu', 'うみかぜ / かいふう', '海風'),
      m('Season', 'kisetsu', 'きせつ', '季節'),
      m('Sky / Heaven', 'sora', 'そら', '空'),
      m('Sleet / Snow with Rain', 'mizore', 'みぞれ', '霙'),
      m('Snow', 'yuki', 'ゆき', '雪'),
      m('Snow', 'yuki', 'ゆき', '雪'),
      m('Space / Universe / Cosmos', 'uchuu', 'うちゅう', '宇宙'),
      m('Spring', 'haru', 'はる', '春'),
      m('Spring Rain', 'shunu / haru same', 'しゅんう / はるさめ', '春雨'),
      m('Star', 'hoshi', 'ほし', '星'),
      m('Stone', 'ishi', 'いし', '石'),
      m('Strong Wind', 'kyoufuu', 'きょうふう', '強風'),
      m('Summer', 'natsu', 'なつ', '夏'),
      m('Sun', 'taiyou', 'たいよう', '太陽'),
      m('Sun', 'ohisama', 'おひさま', 'お日様'),
      m('Sun', 'taiyou', 'たいよう', '太陽'),
      m('Sun Shower / Sudden Rainfall in the Sunshine', 'tenki ame', 'てんきあめ', '天気雨'),
      m('Temperature', 'kion', 'きおん', '気温'),
      m('Thunder', 'kaminari', 'かみなり', '雷'),
      m('Thunder', 'kaminari', 'かみなり', '雷'),
      m('Thunderstorm', 'raiu', 'らいう', '雷雨'),
      m('Tree / Wood', 'ki', 'き', '木'),
      m('Tropical Day', 'ma natsu bi', 'まなつび', '真夏日'),
      m('Tsunami / Tidal Wave', 'tsunami', 'つなみ', '津波'),
      m('Tsunami / Tidal Wave', 'tsunami', 'つなみ', '津波'),
      m('Typhoon', 'taifuu', 'たいふう', '台風'),
      m('Valley', 'tani', 'たに', '谷'),
      m('Volcano', 'kazan', 'かざん', '火山'),
      m('Water', 'mizu', 'みず', '水'),
      m('Water Well', 'i/ido', 'い/いど', '井/井戸'),
      m('Waterfall', 'taki', 'たき', '滝'),
      m('Wave', 'nami', 'なみ', '波'),
      m('Weather', 'tenki', 'てんき', '天気'),
      m('Weather Forecast', 'tenki yohou', 'てんきよほう', '天気予報'),
      m('Weather Front', 'zensen', 'ぜんせん', '前線'),
      m('Whirlwind / Vortex', 'senpuu / tsumuji kaze', 'せんぷう / つむじかぜ', '旋風'),
      m('Wind', 'kaze', 'かぜ', '風'),
      m('Wind / Breeze', 'kaze', 'かぜ', '風'),
      m('Windstorm', 'boufuu', 'ぼうふう', '暴風'),
      m('Winter', 'fuyu', 'ふゆ', '冬'),
      m('Wood / Grove', 'hayashi', 'はやし', '林'),
    ]),

    createSet('Vehicles', 'vehicles', [
      m('Aeroplane / Airplane', 'hikouki', 'ひこうき', '飛行機'),
      m('Airship / Blimp', 'hikousen', 'ひこうせん', '飛行船'),
      m('Ambulance', 'kyuukyuusha', 'きゅうきゅうしゃ', '救急車'),
      m('Automobile', 'jidousha', 'じどうしゃ', '自動車'),
      m('Bicycle', 'jitensha', 'じてんしゃ', '自転車'),
      m('Car / Automobile', 'kuruma', 'くるま', '車'),
      m('Carriage / Horse-drawn Coach', 'basha', 'ばしゃ', '馬車'),
      m('Cruise', 'kuru-zu', 'クルーズ', 'クルーズ'),
      m('Ferry', 'feri-', 'フェリー', 'フェリー'),
      m('Fire Engine / Fire Truck', 'shoubousha', 'しょうぼうしゃ', '消防車'),
      m('Freighter / Cargo Ship', 'kamotsusen', 'かもつせん', '貨物船'),
      m('Monorail', 'monore-ru', 'モノレール', 'モノレール'),
      m('Motorcycle', 'o-tobai', 'オートバイ', 'オートバイ'),
      m('Motorcycle / Motorbike', 'baiku', 'バイク', 'バイク'),
      m('Rickshaw', 'jinrikisha', 'じんりきしゃ', '人力車'),
      m('Rocket', 'roketto', 'ロケット', 'ロケット'),
      m('Scooter', 'suku-ta-', 'スクーター', 'スクーター'),
      m('Shikansen / Bullet Train', 'shinkansen', 'しんかんせん', '新幹線'),
      m('Ship / Boat', 'fune', 'ふね', '船'),
      m('Submarine', 'sensuikan', 'せんすいかん', '潜水艦'),
      m('Subway / Metro / Underground Train', 'chikatetsu', 'ちかてつ', '地下鉄'),
      m('Tractor', 'torakuta-', 'トラクター', 'トラクター'),
      m('Train', 'densha', 'でんしゃ', '電車'),
      m('Tram / City Streetcar / Municipal Railway', 'shiden', 'しでん', '市電'),
      m('Tram / Streetcar / Tramcar', 'romendensha', 'ろめんでんしゃ', '路面電車'),
      m('Transport / Vehicle', 'norimono', 'のりもの', '乗り物'),
      m('Transportation / Traffic', 'koutsuu', 'こうつう', '交通'),
      m('Tricycle / Three Wheeled Vehicle', 'sanrinsha', 'さんりんしゃ', '三輪車'),
      m('Van', 'ban', 'バン', 'バン'),
      m('Wheelchair', 'kurumaisu', 'くるまいす', '車椅子'),
      m('Yacht', 'yotto', 'ヨット', 'ヨット'),
    ]),

    createSet('Business Words', 'business', [
      m('Absence from Work', 'kekkin', 'けっきん', '欠勤'),
      m('Annuity / Pension', 'nenkin', 'ねんきん', '年金'),
      m('Big Enterprise / Well-established Company', 'oote kigyou', 'おおてきぎょう', '大手企業'),
      m('Bonus', 'bo-nasu', 'ボーナス', 'ボーナス'),
      m('Business Card / Name Card', 'meishi', 'めいし', '名刺'),
      m('Business Trip', 'shucchou', 'しゅっちょう', '出張'),
      m('Colleague / Coworker', 'dou ryou', 'どうりょう', '同僚'),
      m('Commuter Rush', 'tsukin rasshu', 'つうきんラッシュ', '通勤ラッシュ'),
      m('Company Director / Board Member', 'tori shimari yaku', 'とりしまりやく', '取締役'),
      m('Company President', 'sha chou', 'しゃちょう', '社長'),
      m('Department Manager', 'bu chou', 'ぶちょう', '部長'),
      m('Development Department', 'kaihatsu bu', 'かいはつぶ', '開発部'),
      m('Document', 'shorui', 'しょるい', '書類'),
      m('Employee / Worker', 'juugyou in', 'じゅうぎょういん', '従業員'),
      m('Enterprise / Company', 'kigyou', 'きぎょう', '企業'),
      m('Executive Director', 'senmu', 'せんむ', '専務'),
      m('General Affairs Department', 'soumu bu', 'そうむぶ', '総務部'),
      m('General Manager', 'Sou shihai nin', 'そうしはいにん', '総支配人'),
      m('Group Leader / Unit Head', 'kakari chou', 'かかりちょう', '係長'),
      m('Guest / Customer / Visitor', 'okyaku san', 'おきゃくさん', 'お客さん'),
      m('Human Resources Department', 'jinji bu', 'じんじぶ', '人事部'),
      m('Insurance', 'hoken', 'ほけん', '保険'),
      m('Interview', 'mensetsu', 'めんせつ', '面接'),
      m('Letter of Resignation', 'jihyou', 'じひょう', '辞表'),
      m('Limited Company', 'yuugen gaisha', 'ゆうげんがいしゃ', '有限会社'),
      m('Meeting', 'kaigi', 'かいぎ', '会議'),
      m('Meeting Room', 'kaigi shitsu', 'かいぎしつ', '会議室'),
      m('Messrs (Addressing the other company at the beginning of letter)', 'onchuu', 'おんちゅう', '御中'),
      m('New Product', 'shin seihin', 'しんせいひん', '新製品'),
      m('Office', 'jimu sho', 'じむしょ', '事務所'),
      m('Office Clerk', 'jimu in', 'じむいん', '事務員'),
      m('Overtime Work', 'zan gyou', 'ざんぎょう', '残業'),
      m('Paid Leave', 'yuukyuu kyuuka', 'ゆうきゅうきゅうか', '有給休暇'),
      m('Personal Seal', 'hanko', 'はんこ', '判子'),
      m('Personal Seal', 'inkan', 'いんかん', '印鑑'),
      m('Photocopier', 'kopi-ki', 'コピーき', 'コピー機'),
      m('Project Proposal', 'kikaku sho', 'きかくしょ', '企画書'),
      m('Reception Area / Information Area', 'uke tsuke', 'うけつけ', '受付'),
      m('Report of Absence / Notice of Absence', 'kekkin todoke', 'けっきんとどけ', '欠勤届'),
      m('Salary / Wage / Pay', 'kyuuryou', 'きゅうりょう', '給料'),
      m('Sales Department', 'eigyou bu', 'えいぎょうぶ', '営業部'),
      m('Section Manager', 'ka chou', 'かちょう', '課長'),
      m('Sincerely Yours (Used at the end of letter)', 'keigu', 'けいぐ', '敬具'),
      m('Small to Medium Enterprise', 'chuushou kigyou', 'ちゅうしょうきぎょう', '中小企業'),
      m('Subordinate', 'buka', 'ぶか', '部下'),
      m('Superior / Boss', 'joushi', 'じょうし', '上司'),
      m('Telephone', 'denwa', 'でんわ', '電話'),
      m('Temporary Worker', 'haken shain', 'はけんしゃいん', '派遣社員'),
      m('Temporary Worker Agency', 'haken gaisha', 'はけんがいしゃ', '派遣会社'),
      m('Vice President', 'fuku sha shou', 'ふくしゃちょう', '副社長'),
    ]),
  ];

      // m('ENGLISH', 'ROMAJI', 'KANA', 'KANJI'),

  let allWords = [];
  output.forEach(set => {
    set.words.forEach(word => {
      allWords.push({ ...word }); // id value is overwritten by createSet
    });
  });

  return [
    createSet('Everything Combined', 'everything', allWords),
    ...output,
  ];

  // TODO: https://cotoacademy.com/japanese-it-vocabulary/
  // TODO: https://www.learn-japanese-adventure.com/japanese-words.html
})();